(()=>{
'use strict';
if(window.__NOVABEAT_MODELS_V2__) return;
window.__NOVABEAT_MODELS_V2__=true;
const $=s=>document.querySelector(s);
const promptEl=$('#prompt'),styleEl=$('#style'),moodEl=$('#mood'),durEl=$('#duration'),btn=$('#generate'),result=$('#result'),empty=$('#emptyState'),audio=$('#audio'),dl=$('#download'),dot=$('#statusDot'),status=$('#statusText'),support=$('#supportText');
if(!promptEl||!btn||!audio) return;
const CSS=`
.nb2-model-field{margin-bottom:16px}.nb2-label{font-size:13px;color:#dedee7;font-weight:800;margin-bottom:8px}.nb2-sub{font-size:12px;color:#a6a6b7;margin:-3px 0 10px;line-height:1.5}.nb2-model-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.nb2-model{position:relative;text-align:right;border:1px solid #29293a;background:#0d0d15;color:#ededf5;border-radius:15px;padding:12px;cursor:pointer;min-height:116px;transition:.18s;font:inherit}.nb2-model:hover{transform:translateY(-1px);border-color:#625c85}.nb2-model.active{border-color:#785fff;background:linear-gradient(180deg,#211b3b,#131322);box-shadow:0 0 0 3px rgba(121,92,255,.09)}.nb2-model.best{border-color:#3e6f69}.nb2-model.best.active{border-color:#45d6c7;background:linear-gradient(180deg,#12312f,#131923)}.nb2-model .num{font-size:11px;color:#a9a3ca}.nb2-model b{display:block;margin:4px 0 5px;font-size:14px}.nb2-model small{display:block;color:#a6a6b7;line-height:1.45;font-size:11px}.nb2-best-tag{position:absolute;left:8px;top:8px;background:#123b36;color:#8af4e7;border:1px solid #2a6c64;border-radius:999px;padding:3px 6px;font-size:9px;font-weight:900}.nb2-quality{margin-top:12px;border-top:1px solid #29293a;padding-top:10px;display:grid;gap:5px}.nb2-q{display:flex;justify-content:space-between;gap:10px;font-size:11px;color:#a6a6b7}.nb2-q strong{color:#ddd}.nb2-model-badge{display:inline-block;margin-top:7px;padding:4px 7px;border-radius:999px;background:#17172a;border:1px solid #39355a;color:#d9d4ff;font-size:10px;font-weight:800}@media(max-width:760px){.nb2-model-grid{grid-template-columns:1fr}.nb2-model{min-height:auto}}
`;
const st=document.createElement('style');st.id='novabeat-models-v2-style';st.textContent=CSS;document.head.appendChild(st);
const modelField=document.createElement('div');modelField.className='nb2-model-field';modelField.innerHTML=`<div class="nb2-label">الموديل</div><div class="nb2-sub">الثلاثة محركات مختلفة فعليًا. Model 3 هو الأفضل في كل شيء.</div><div class="nb2-model-grid"><button class="nb2-model" data-nb2-model="lite" type="button"><span class="num">MODEL 1</span><b>Nova Lite 1</b><small>الأسرع والأخف — طبقات أقل وصوت مباشر.</small></button><button class="nb2-model" data-nb2-model="studio" type="button"><span class="num">MODEL 2</span><b>Nova Studio 2</b><small>ستيريو، Humanization، FX وتوزيع أغنى.</small></button><button class="nb2-model best active" data-nb2-model="ultra" type="button"><span class="nb2-best-tag">BEST</span><span class="num">MODEL 3</span><b>Nova Ultra 3</b><small>48 kHz، أفضل درامز وباس وهارموني وTransitions وMastering.</small></button></div>`;
promptEl.closest('.field').insertAdjacentElement('afterend',modelField);
const quality=document.createElement('div');quality.id='novabeatQualityV2';quality.className='nb2-quality';quality.innerHTML=`<div class="nb2-q"><span>Model</span><strong id="nb2ModelSpec">Nova Ultra 3</strong></div><div class="nb2-q"><span>Sample rate</span><strong id="nb2RateSpec">48 kHz</strong></div><div class="nb2-q"><span>Mix engine</span><strong id="nb2MixSpec">Premium stereo + mastering</strong></div>`;
const specs=$('.specs');if(specs) specs.insertAdjacentElement('afterend',quality);
const brandP=$('.brand p');if(brandP) brandP.textContent='3 محركات صوت — Model 3 أعلى جودة';
const heroP=document.querySelector('.hero>p');if(heroP) heroP.textContent='اختار واحدًا من 3 موديلات حقيقية مختلفة في جودة الرندر والتوزيع. Nova Ultra 3 هو الأفضل في كل شيء ويستخدم أعلى جودة صوت وأغنى توزيع.';
let selectedModel='ultra',currentUrl=null,nonce=0;
const NOTES=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];
const STYLE={trap:{bpm:92,bass:'sine',lead:'triangle',kick:[0,2.5],snare:[1,3]},pop:{bpm:116,bass:'triangle',lead:'sine',kick:[0,2],snare:[1,3]},lofi:{bpm:80,bass:'triangle',lead:'triangle',kick:[0,2.25],snare:[1,3]},edm:{bpm:128,bass:'sawtooth',lead:'sawtooth',kick:[0,1,2,3],snare:[1,3]},cinematic:{bpm:96,bass:'sine',lead:'triangle',kick:[0,2],snare:[1,3]}};
const MOOD={dark:{root:1,scale:[0,2,3,5,7,8,10],prog:[0,5,3,6]},uplifting:{root:0,scale:[0,2,4,5,7,9,11],prog:[0,4,5,3]},dreamy:{root:9,scale:[0,2,4,7,9],prog:[0,3,5,4]},epic:{root:2,scale:[0,2,3,5,7,8,10],prog:[0,5,6,4]},calm:{root:5,scale:[0,2,4,5,7,9,11],prog:[0,3,4,0]}};
const MODELS={lite:{name:'Nova Lite 1',short:'Lite 1',rate:24000,channels:1,layers:4,human:.003,reverb:.018,delay:false,quality:'Fast mix'},studio:{name:'Nova Studio 2',short:'Studio 2',rate:44100,channels:2,layers:7,human:.006,reverb:.07,delay:true,quality:'Studio stereo'},ultra:{name:'Nova Ultra 3',short:'Ultra 3',rate:48000,channels:2,layers:11,human:.010,reverb:.105,delay:true,quality:'Premium stereo + mastering'}};
function hash(s){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
const midi=n=>440*Math.pow(2,(n-69)/12);
function panNode(ctx,p){if(ctx.createStereoPanner){const x=ctx.createStereoPanner();x.pan.value=Math.max(-1,Math.min(1,p));return x}return ctx.createGain()}
function env(g,t,peak,attack,hold,release){g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.0002,peak),t+attack);g.gain.setValueAtTime(Math.max(.0002,peak*.82),t+attack+hold);g.gain.exponentialRampToValueAtTime(.0001,t+attack+hold+release)}
function tone(ctx,dest,t,dur,freq,type,gain=.08,pan=0,detune=0,cutoff=0){const o=ctx.createOscillator(),g=ctx.createGain(),p=panNode(ctx,pan);o.type=type;o.frequency.setValueAtTime(freq,t);o.detune.value=detune;env(g,t,gain,.008,Math.max(.02,dur-.09),.08);o.connect(g);if(cutoff){const f=ctx.createBiquadFilter();f.type='lowpass';f.frequency.value=cutoff;g.connect(f);f.connect(p)}else g.connect(p);p.connect(dest);o.start(t);o.stop(t+dur+.12)}
function pluck(ctx,dest,t,dur,freq,gain,pan,type='triangle'){const o=ctx.createOscillator(),g=ctx.createGain(),f=ctx.createBiquadFilter(),p=panNode(ctx,pan);o.type=type;o.frequency.value=freq;f.type='lowpass';f.frequency.setValueAtTime(Math.min(4800,freq*6.5),t);f.Q.value=.8;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(gain,t+.006);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(f);f.connect(g);g.connect(p);p.connect(dest);o.start(t);o.stop(t+dur+.04)}
function noiseBuffer(ctx,seconds=.22){const b=ctx.createBuffer(1,Math.max(1,Math.floor(ctx.sampleRate*seconds)),ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;return b}
function kick(ctx,dest,t,amp=.72){t=Math.max(0,t);amp*=.94+Math.random()*.1;const body=ctx.createOscillator(),bg=ctx.createGain(),click=ctx.createBufferSource(),cf=ctx.createBiquadFilter(),cg=ctx.createGain();body.type='sine';body.frequency.setValueAtTime(118,t);body.frequency.exponentialRampToValueAtTime(49,t+.12);bg.gain.setValueAtTime(amp,t);bg.gain.exponentialRampToValueAtTime(.0001,t+.31);click.buffer=noiseBuffer(ctx,.018);cf.type='highpass';cf.frequency.value=2700;cg.gain.setValueAtTime(amp*.06,t);cg.gain.exponentialRampToValueAtTime(.0001,t+.018);body.connect(bg);bg.connect(dest);click.connect(cf);cf.connect(cg);cg.connect(dest);body.start(t);body.stop(t+.33);click.start(t)}
function snare(ctx,dest,t,amp=.22,pan=0){t=Math.max(0,t);amp*=.9+Math.random()*.16;const src=ctx.createBufferSource(),f=ctx.createBiquadFilter(),g=ctx.createGain(),p=panNode(ctx,pan),body=ctx.createOscillator(),bg=ctx.createGain();src.buffer=noiseBuffer(ctx,.19);f.type='bandpass';f.frequency.value=1550;f.Q.value=.62;g.gain.setValueAtTime(amp,t);g.gain.exponentialRampToValueAtTime(.0001,t+.17);body.type='triangle';body.frequency.setValueAtTime(196,t);body.frequency.exponentialRampToValueAtTime(145,t+.09);bg.gain.setValueAtTime(amp*.15,t);bg.gain.exponentialRampToValueAtTime(.0001,t+.11);src.connect(f);f.connect(g);g.connect(p);body.connect(bg);bg.connect(p);p.connect(dest);src.start(t);body.start(t);body.stop(t+.12)}
function hat(ctx,dest,t,amp=.07,pan=0){t=Math.max(0,t);amp*=.82+Math.random()*.28;const src=ctx.createBufferSource(),hp=ctx.createBiquadFilter(),bp=ctx.createBiquadFilter(),g=ctx.createGain(),p=panNode(ctx,pan);src.buffer=noiseBuffer(ctx,.06);hp.type='highpass';hp.frequency.value=7200;bp.type='bandpass';bp.frequency.value=9800;bp.Q.value=.55;g.gain.setValueAtTime(amp*.82,t);g.gain.exponentialRampToValueAtTime(.0001,t+.05);src.connect(hp);hp.connect(bp);bp.connect(g);g.connect(p);p.connect(dest);src.start(t)}
function shaker(ctx,dest,t,amp=.028,pan=0){t=Math.max(0,t);amp*=.78+Math.random()*.3;const src=ctx.createBufferSource(),f=ctx.createBiquadFilter(),g=ctx.createGain(),p=panNode(ctx,pan);src.buffer=noiseBuffer(ctx,.1);f.type='bandpass';f.frequency.value=4300+Math.random()*800;f.Q.value=.65;g.gain.setValueAtTime(.0001,t);g.gain.linearRampToValueAtTime(amp,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+.09);src.connect(f);f.connect(g);g.connect(p);p.connect(dest);src.start(t)}
function createBus(ctx,key){const model=MODELS[key],input=ctx.createGain(),dry=ctx.createGain(),wet=ctx.createGain();dry.gain.value=1;wet.gain.value=model.reverb;input.connect(dry);let masterIn=ctx.createGain();dry.connect(masterIn);if(model.reverb>0){const conv=ctx.createConvolver(),seconds=key==='ultra'?2.1:1.2,len=Math.floor(ctx.sampleRate*seconds),imp=ctx.createBuffer(2,len,ctx.sampleRate);for(let c=0;c<2;c++){const d=imp.getChannelData(c);for(let i=0;i<len;i++){const decay=Math.pow(1-i/len,key==='ultra'?2.6:3.6);d[i]=(Math.random()*2-1)*decay}}conv.buffer=imp;input.connect(conv);conv.connect(wet);wet.connect(masterIn)}if(model.delay){const d=ctx.createDelay(1),fb=ctx.createGain(),dg=ctx.createGain();d.delayTime.value=key==='ultra'?.23:.17;fb.gain.value=key==='ultra'?.10:.07;dg.gain.value=key==='ultra'?.045:.035;input.connect(d);d.connect(fb);fb.connect(d);d.connect(dg);dg.connect(masterIn)}const hp=ctx.createBiquadFilter();hp.type='highpass';hp.frequency.value=25;masterIn.connect(hp);let tail=hp;if(key==='ultra'){const shelf=ctx.createBiquadFilter();shelf.type='highshelf';shelf.frequency.value=7800;shelf.gain.value=.75;tail.connect(shelf);tail=shelf;const sat=ctx.createWaveShaper(),curve=new Float32Array(4096);for(let i=0;i<curve.length;i++){const x=i*2/(curve.length-1)-1;curve[i]=Math.tanh(x*1.08)}sat.curve=curve;sat.oversample='4x';tail.connect(sat);tail=sat}const comp=ctx.createDynamicsCompressor();comp.threshold.value=key==='ultra'?-14:-11;comp.knee.value=20;comp.ratio.value=key==='ultra'?2.5:3.2;comp.attack.value=.009;comp.release.value=.24;tail.connect(comp);const out=ctx.createGain();out.gain.value=key==='lite'?.75:.7;comp.connect(out);out.connect(ctx.destination);return input}
function chordNotes(rootMidi,scale,degree,rich){const a=scale[degree%scale.length],b=scale[(degree+2)%scale.length]+(degree+2>=scale.length?12:0),c=scale[(degree+4)%scale.length]+(degree+4>=scale.length?12:0),arr=[rootMidi+a,rootMidi+b,rootMidi+c];if(rich)arr.push(rootMidi+scale[(degree+6)%scale.length]+12);return arr}
const humanTime=(r,a)=>(r()-.5)*a;
async function renderTrack(opts){const model=MODELS[opts.model],style=STYLE[opts.style],mood=MOOD[opts.mood],rate=model.rate,channels=model.channels,frames=Math.ceil(opts.duration*rate),Offline=window.OfflineAudioContext||window.webkitOfflineAudioContext,ctx=new Offline(channels,frames,rate),bus=createBus(ctx,opts.model),r=rng(opts.seed),beat=60/style.bpm,bar=beat*4,base=48+mood.root,prog=mood.prog,scale=mood.scale,end=opts.duration-.15;
for(let t=0,barIdx=0;t<end;t+=bar,barIdx++){const deg=prog[barIdx%prog.length]%scale.length,notes=chordNotes(base,scale,deg,opts.model==='ultra'),intro=t<opts.duration*.15,amp=intro?.025:(opts.model==='lite'?.038:opts.model==='studio'?.05:.056);notes.forEach((n,i)=>{const p=channels===1?0:(i-(notes.length-1)/2)*.2;tone(ctx,bus,t,Math.min(bar+.12,end-t),midi(n),opts.style==='cinematic'?'sine':(opts.model==='lite'?'triangle':opts.model==='studio'?'triangle':'triangle'),amp/notes.length,p,opts.model==='ultra'?(i%2?5:-5):0,opts.model==='ultra'?3300:2600);if(opts.model==='ultra')tone(ctx,bus,t+.008,Math.min(bar,end-t),midi(n+12),'triangle',amp/(notes.length*2.8),-p,(i%2?-8:8),5200)})}
for(let t=0,step=0;t<end;t+=beat/2,step++){const barIdx=Math.floor(t/bar),deg=prog[barIdx%prog.length]%scale.length,root=base-12+scale[deg],hit=opts.model==='lite'?step%2===0:(opts.model==='studio'?(step%2===0||step%8===5):(step%2===0||step%8===3||step%8===7));if(!hit||t<opts.duration*.08)continue;const len=opts.model==='ultra'?beat*.42:beat*.34,ht=humanTime(r,model.human);tone(ctx,bus,Math.max(0,t+ht),len,midi(root),style.bass,opts.model==='lite'?.085:opts.model==='studio'?.09:.095,0,0,opts.model==='ultra'?950:1250);if(opts.model==='ultra')tone(ctx,bus,Math.max(0,t+ht),len*.8,midi(root-12),'sine',.055,0,0,420)}
for(let t=0,step=0;t<end;t+=beat/4,step++){const pos=(step%16)/4,phase=t/opts.duration,intro=phase<.13,outro=phase>.9;if(!intro){if(style.kick.some(x=>Math.abs(pos-x)<.08))kick(ctx,bus,Math.max(0,t+humanTime(r,model.human)),opts.model==='ultra'?.62:.55);if(style.snare.some(x=>Math.abs(pos-x)<.08))snare(ctx,bus,Math.max(0,t+humanTime(r,model.human)),opts.model==='ultra'?.19:.17,channels===1?0:.04)}if(opts.model!=='lite'&&!outro&&step%2===0)hat(ctx,bus,Math.max(0,t+humanTime(r,model.human)),opts.model==='ultra'?.045:.035,channels===1?0:(step%4?-.28:.28));if(opts.model==='ultra'&&!intro&&step%2===1)shaker(ctx,bus,Math.max(0,t+humanTime(r,model.human)),.021,step%4===1?-.48:.48)}
const leadStep=opts.model==='lite'?beat:beat/2;let lastDegree=0;for(let t=beat*2,i=0;t<end;t+=leadStep,i++){const phase=t/opts.duration;if(phase<.15||r()<.18)continue;let jump=Math.floor(r()*5)-2;lastDegree=Math.max(0,Math.min(scale.length-1,lastDegree+jump));const note=60+mood.root+scale[lastDegree]+(r()>.82?12:0),pan=channels===1?0:((r()-.5)*(opts.model==='ultra'?.65:.32)),ht=humanTime(r,model.human),len=opts.model==='ultra'?beat*.62:beat*.42;pluck(ctx,bus,Math.max(0,t+ht),len,midi(note),opts.model==='lite'?.055:opts.model==='studio'?.062:.068,pan,style.lead);if(opts.model==='ultra'&&i%8===6)pluck(ctx,bus,Math.max(0,t+ht+.01),len*.8,midi(note+7),.009,-pan*.5,'sine')}
const buffer=await ctx.startRendering();smoothEdges(buffer);normalizeBuffer(buffer,opts.model==='ultra'?.91:.88);return buffer}
function smoothEdges(buffer){const sr=buffer.sampleRate,n=buffer.length,fi=Math.min(Math.floor(sr*.25),Math.floor(n*.08)),fo=Math.min(Math.floor(sr*1.15),Math.floor(n*.16));for(let c=0;c<buffer.numberOfChannels;c++){const d=buffer.getChannelData(c);for(let i=0;i<fi;i++)d[i]*=i/Math.max(1,fi);for(let i=0;i<fo;i++){const j=n-1-i;d[j]*=i/Math.max(1,fo)}}}
function normalizeBuffer(buffer,target){let peak=0;for(let c=0;c<buffer.numberOfChannels;c++){const d=buffer.getChannelData(c);for(let i=0;i<d.length;i++){const a=Math.abs(d[i]);if(a>peak)peak=a}}if(peak>.0001){const gain=Math.min(1.35,target/peak);for(let c=0;c<buffer.numberOfChannels;c++){const d=buffer.getChannelData(c);for(let i=0;i<d.length;i++)d[i]=Math.max(-1,Math.min(1,d[i]*gain))}}}
function wavBlob(buffer){const channels=buffer.numberOfChannels,rate=buffer.sampleRate,frames=buffer.length,bytes=44+frames*channels*2,ab=new ArrayBuffer(bytes),v=new DataView(ab);let p=0;const s=x=>{for(let i=0;i<x.length;i++)v.setUint8(p++,x.charCodeAt(i))};s('RIFF');v.setUint32(p,bytes-8,true);p+=4;s('WAVE');s('fmt ');v.setUint32(p,16,true);p+=4;v.setUint16(p,1,true);p+=2;v.setUint16(p,channels,true);p+=2;v.setUint32(p,rate,true);p+=4;v.setUint32(p,rate*channels*2,true);p+=4;v.setUint16(p,channels*2,true);p+=2;v.setUint16(p,16,true);p+=2;s('data');v.setUint32(p,frames*channels*2,true);p+=4;const data=Array.from({length:channels},(_,c)=>buffer.getChannelData(c));for(let i=0;i<frames;i++)for(let c=0;c<channels;c++){const x=Math.max(-1,Math.min(1,data[c][i]));v.setInt16(p,x<0?x*32768:x*32767,true);p+=2}return new Blob([ab],{type:'audio/wav'})}
function titleFromPrompt(text,style){const cleaned=text.trim().replace(/\s+/g,' ');if(cleaned)return cleaned.slice(0,34)+(cleaned.length>34?'…':'');return ({trap:'Night Run',pop:'Summer Light',lofi:'Quiet Room',edm:'Neon Pulse',cinematic:'Final Horizon'})[style]}
function setWorking(msg){dot.className='dot work';status.textContent=msg;btn.disabled=true}
function setReady(msg){dot.className='dot on';status.textContent=msg;btn.disabled=false}
function setError(msg){dot.className='dot bad';status.textContent=msg;btn.disabled=false}
function updateQuality(){const m=MODELS[selectedModel];$('#nb2ModelSpec').textContent=m.name;$('#nb2RateSpec').textContent=(m.rate/1000).toFixed(m.rate%1000?1:0)+' kHz';$('#nb2MixSpec').textContent=m.quality;btn.textContent=`✨ توليد الأغنية — ${m.name}`}
function selectModel(key){selectedModel=key;document.querySelectorAll('[data-nb2-model]').forEach(x=>x.classList.toggle('active',x.dataset.nb2Model===key));updateQuality()}
async function generate(){const id=++nonce,model=MODELS[selectedModel],duration=+durEl.value,seed=hash(promptEl.value+'|'+styleEl.value+'|'+moodEl.value+'|'+selectedModel+'|'+Date.now());setWorking(selectedModel==='ultra'?'Nova Ultra 3 يبني التوزيع والـMastering…':'جاري توليد الموسيقى…');try{await new Promise(r=>setTimeout(r,50));const buffer=await renderTrack({model:selectedModel,style:styleEl.value,mood:moodEl.value,duration,seed});if(id!==nonce)return;const blob=wavBlob(buffer);if(currentUrl)URL.revokeObjectURL(currentUrl);currentUrl=URL.createObjectURL(blob);audio.src=currentUrl;dl.href=currentUrl;dl.download=`novabeat-${selectedModel}-${Date.now()}.wav`;empty.style.display='none';result.classList.add('show');$('#trackTitle').textContent=titleFromPrompt(promptEl.value,styleEl.value);$('#trackMeta').innerHTML=`${model.name} • ${styleEl.options[styleEl.selectedIndex].text} • ${moodEl.options[moodEl.selectedIndex].text} • WAV <span class="nb2-model-badge">${model.rate/1000} kHz / ${model.channels===2?'Stereo':'Mono'}</span>`;$('#bpmSpec').textContent=STYLE[styleEl.value].bpm;$('#keySpec').textContent=NOTES[MOOD[moodEl.value].root];$('#durSpec').textContent=duration+'s';updateQuality();setReady('تم التوليد بنجاح — '+model.name+' جاهز للتشغيل.')}catch(e){console.error(e);setError('حصل خطأ أثناء التوليد: '+(e&&e.message?e.message:'غير معروف'))}}
document.querySelectorAll('[data-nb2-model]').forEach(x=>x.addEventListener('click',()=>selectModel(x.dataset.nb2Model)));
btn.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();generate()},true);
const regen=$('#regenerate');if(regen)regen.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();generate()},true);
const self=$('#selfTest');if(self)self.addEventListener('click',async e=>{e.preventDefault();e.stopImmediatePropagation();support.textContent='جارٍ اختبار Model 3 ورندر صوت حقيقي…';try{const b=await renderTrack({model:'ultra',style:'pop',mood:'uplifting',duration:2,seed:12345});let sum=0,d=b.getChannelData(0),skip=Math.max(1,Math.floor(d.length/12000));for(let i=0;i<d.length;i+=skip)sum+=d[i]*d[i];const rms=Math.sqrt(sum/Math.ceil(d.length/skip));if(rms>.002) support.textContent=`نجح ✓ — Model 3 Render غير صامت (RMS ${rms.toFixed(3)})`;else throw new Error('silent render')}catch(err){support.textContent='فشل الاختبار: '+err.message}},true);
if(window.OfflineAudioContext||window.webkitOfflineAudioContext){support.textContent='المتصفح يدعم محركات Nova Lite / Studio / Ultra ✓'}else{support.textContent='المتصفح لا يدعم محرك الصوت المطلوب';btn.disabled=true;dot.className='dot bad'}
selectModel('ultra');
})();
