import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.185.1/build/three.module.min.js';

const $=s=>document.querySelector(s);const screens={menu:$('#menu'),select:$('#select'),game:$('#game')};
const teams=[
{name:'Nova City',short:'NOVA',a:0xb8ff38,b:0x2ce5b1,rating:84},{name:'Orbit United',short:'ORBT',a:0x36e8ff,b:0x7057ff,rating:82},{name:'Metro Athletic',short:'MTRA',a:0xff5b68,b:0xffb25b,rating:83},{name:'Harbour FC',short:'HBR',a:0x6fa8ff,b:0xd6e7ff,rating:80},{name:'Royal Vale',short:'VALE',a:0xffd166,b:0xfff0aa,rating:85},{name:'Pulse 04',short:'PLS',a:0xec5cff,b:0xff9eea,rating:81},{name:'Northstar',short:'NSTR',a:0xf1f5f9,b:0x86efac,rating:79},{name:'Redline SC',short:'RDLN',a:0xff365d,b:0x8b1735,rating:84}
];
let mode='quick',selected=0,cupStage=Number(localStorage.pitch27CupStage||0),raf=0,last=0;
const state={running:false,paused:false,time:0,duration:180,score:[0,0],players:[],ball:null,controlled:0,joy:{x:0,y:0},sprint:false,homeTeam:0,awayTeam:1};
let renderer,scene,camera,world,ballMesh,indicator,quality='high';const playerMeshes=[];
function show(name){Object.values(screens).forEach(s=>s.classList.remove('active'));screens[name].classList.add('active')}
function buildTeams(){
  $('#teams').innerHTML=teams.map((t,i)=>`<button class="team ${i===selected?'selected':''}" data-i="${i}" style="--team1:#${t.a.toString(16).padStart(6,'0')};--team2:#${t.b.toString(16).padStart(6,'0')}"><div class="crest">${t.short.slice(0,2)}</div><b>${t.name}</b><span>OVR ${t.rating}</span></button>`).join('');
  document.querySelectorAll('.team').forEach(el=>el.onclick=()=>{selected=+el.dataset.i;buildTeams()});
}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;buildTeams();show('select')});$('#backMenu').onclick=()=>show('menu');$('#randomTeam').onclick=()=>{selected=Math.floor(Math.random()*teams.length);buildTeams()};$('#kickoff').onclick=()=>startMatch();
function init3D(){
  const canvas=$('#stage');
  renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
  quality=(navigator.deviceMemory&&navigator.deviceMemory<=4)?'balanced':'high';renderer.setPixelRatio(Math.min(devicePixelRatio,quality==='high'?1.65:1.25));
  scene=new THREE.Scene();scene.background=new THREE.Color(0x07120e);scene.fog=new THREE.Fog(0x07120e,70,145);
  camera=new THREE.PerspectiveCamera(54,innerWidth/innerHeight,.1,230);camera.position.set(-15,13,20);
  scene.add(new THREE.HemisphereLight(0xb7d8ff,0x12331f,1.65));const sun=new THREE.DirectionalLight(0xffffff,2.35);sun.position.set(-25,46,22);sun.castShadow=true;sun.shadow.mapSize.set(quality==='high'?2048:1024,quality==='high'?2048:1024);sun.shadow.camera.left=-75;sun.shadow.camera.right=75;sun.shadow.camera.top=55;sun.shadow.camera.bottom=-55;scene.add(sun);
  buildWorld();resize3D();addEventListener('resize',resize3D);
}
function mat(color,rough=.72,metal=.02){return new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal})}
function mesh(geo,material,cast=true,receive=true){const m=new THREE.Mesh(geo,material);m.castShadow=cast;m.receiveShadow=receive;return m}
function buildWorld(){
  world=new THREE.Group();scene.add(world);
  const outer=mesh(new THREE.PlaneGeometry(150,112),mat(0x14271d,.96),false,true);outer.rotation.x=-Math.PI/2;outer.position.y=-.05;world.add(outer);
  const pitch=mesh(new THREE.PlaneGeometry(104,68),mat(0x147342,.9),false,true);pitch.rotation.x=-Math.PI/2;world.add(pitch);
  for(let i=0;i<13;i++){const stripe=mesh(new THREE.PlaneGeometry(8,67.8),new THREE.MeshBasicMaterial({color:i%2?0x147342:0x176f42,transparent:true,opacity:.36}),false,false);stripe.rotation.x=-Math.PI/2;stripe.position.set(-48+i*8,.012,0);world.add(stripe)}
  const lineMat=new THREE.LineBasicMaterial({color:0xeaffee,transparent:true,opacity:.92});const line=(pts)=>{const g=new THREE.BufferGeometry().setFromPoints(pts.map(([x,z])=>new THREE.Vector3(x,.035,z)));world.add(new THREE.Line(g,lineMat))};
  line([[-50,-32],[50,-32],[50,32],[-50,32],[-50,-32]]);line([[0,-32],[0,32]]);line([[-50,-19],[-38,-19],[-38,19],[-50,19]]);line([[50,-19],[38,-19],[38,19],[50,19]]);line([[-50,-9],[-44,-9],[-44,9],[-50,9]]);line([[50,-9],[44,-9],[44,9],[50,9]]);
  const circlePts=[];for(let i=0;i<=64;i++){const a=i/64*Math.PI*2;circlePts.push([Math.cos(a)*9.15,Math.sin(a)*9.15])}line(circlePts);
  const spot=mesh(new THREE.CircleGeometry(.28,16),new THREE.MeshBasicMaterial({color:0xffffff}),false,false);spot.rotation.x=-Math.PI/2;spot.position.y=.04;world.add(spot);
  buildGoal(-51.1,Math.PI/2);buildGoal(51.1,-Math.PI/2);buildStands();buildLights();
}
function buildGoal(x,rot){const g=new THREE.Group();g.position.x=x;g.rotation.y=rot;const white=mat(0xf7fff9,.42,.1);const bar=(sx,sy,sz,px,py,pz)=>{const b=mesh(new THREE.BoxGeometry(sx,sy,sz),white);b.position.set(px,py,pz);g.add(b)};bar(.18,3.3,.18,0,1.65,-7.6);bar(.18,3.3,.18,0,1.65,7.6);bar(.18,.18,15.4,0,3.3,0);bar(2.7,.12,.12,-1.3,.15,-7.6);bar(2.7,.12,.12,-1.3,.15,7.6);const net=new THREE.LineBasicMaterial({color:0xc9f7dc,transparent:true,opacity:.32});for(let z=-7.6;z<=7.61;z+=1.5){const geo=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(0,.15,z),new THREE.Vector3(-2.6,.15,z),new THREE.Vector3(-2.6,3,z)]);g.add(new THREE.Line(geo,net))}world.add(g)}
function buildStands(){const standMat=mat(0x182520,.9),seat1=mat(0x27372f,.88),seat2=mat(0x31483c,.88);const addStand=(w,d,x,z,ry=0)=>{const g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=ry;for(let i=0;i<4;i++){const tier=mesh(new THREE.BoxGeometry(w,2.2,d),i%2?seat1:seat2,false,true);tier.position.set(0,1.1+i*1.6,-i*1.25);g.add(tier)}const base=mesh(new THREE.BoxGeometry(w,1.2,d+5),standMat,false,true);base.position.y=.6;g.add(base);world.add(g)};addStand(112,6,0,-40);addStand(112,6,0,40,Math.PI);addStand(68,6,-60,0,Math.PI/2);addStand(68,6,60,0,-Math.PI/2)}
function buildLights(){const poleMat=mat(0x6f8077,.48,.45);[[-55,-38],[-55,38],[55,-38],[55,38]].forEach(([x,z])=>{const p=mesh(new THREE.CylinderGeometry(.18,.28,16,8),poleMat,false,true);p.position.set(x,8,z);world.add(p);const rig=mesh(new THREE.BoxGeometry(4.6,.5,.7),mat(0xe8fff8,.25,.2),false,false);rig.position.set(x,16,z);world.add(rig);const glow=new THREE.PointLight(0xe5fff4,.55,58,2);glow.position.set(x,15,z);scene.add(glow)})}
function createPlayerVisual(teamIdx){const t=teams[teamIdx],g=new THREE.Group();const skin=mat(0xd69a70,.78),shirt=mat(t.a,.57),sock=mat(t.a,.66),boot=mat(0x101817,.48,.08);const torso=mesh(new THREE.CapsuleGeometry(.56,1.05,4,8),shirt);torso.position.y=2.05;g.add(torso);const head=mesh(new THREE.SphereGeometry(.39,14,10),skin);head.position.y=3.12;g.add(head);const hair=mesh(new THREE.SphereGeometry(.405,12,8,0,Math.PI*2,0,Math.PI*.48),mat(0x201713,.88));hair.position.y=3.18;g.add(hair);g.userData.legs=[];[-.28,.28].forEach(z=>{const pivot=new THREE.Group();pivot.position.set(0,1.23,z);const leg=mesh(new THREE.CapsuleGeometry(.17,.72,3,6),sock);leg.position.y=-.45;pivot.add(leg);const foot=mesh(new THREE.BoxGeometry(.52,.22,.32),boot);foot.position.set(.15,-.93,0);pivot.add(foot);g.add(pivot);g.userData.legs.push(pivot)});return g}
function rebuildActors(){playerMeshes.forEach(m=>scene.remove(m));playerMeshes.length=0;state.players.forEach(p=>{const v=createPlayerVisual(p.team?state.awayTeam:state.homeTeam);scene.add(v);playerMeshes.push(v)});if(ballMesh)scene.remove(ballMesh);ballMesh=mesh(new THREE.SphereGeometry(.62,20,14),mat(0xf9fff9,.45,.02));scene.add(ballMesh);if(indicator)scene.remove(indicator);indicator=mesh(new THREE.RingGeometry(.82,1.08,32),new THREE.MeshBasicMaterial({color:0xb8ff38,side:THREE.DoubleSide,transparent:true,opacity:.92}),false,false);indicator.rotation.x=-Math.PI/2;scene.add(indicator)}
function resize3D(){if(!renderer||!camera)return;const w=Math.max(1,innerWidth),h=Math.max(1,innerHeight);camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)}
function randOpponent(){let n;do n=Math.floor(Math.random()*teams.length);while(n===selected);return n}
function startMatch(){cancelAnimationFrame(raf);show('game');state.homeTeam=selected;state.awayTeam=randOpponent();state.duration=mode==='training'?Infinity:mode==='tournament'?150:180;state.time=0;state.score=[0,0];state.running=true;state.paused=false;state.sprint=false;setupMatch();rebuildActors();updateHud();$('#pauseOverlay').classList.remove('show');$('#resultOverlay').classList.remove('show');$('#modeChip').textContent=mode==='tournament'?`CUP • ROUND ${cupStage+1}/3`:mode==='training'?'TRAINING':'QUICK MATCH';last=performance.now();raf=requestAnimationFrame(loop)}
function setupMatch(){state.players=[];const form=[[-39,0],[-21,-18],[-21,18],[-6,-9],[-6,9]];for(let team=0;team<2;team++)for(let i=0;i<5;i++){const [x,z]=form[i];state.players.push({team,i,x:team?-x:x,z,vx:0,vz:0,has:false,cool:0,face:team?Math.PI:0})}state.ball={x:0,y:.62,z:0,vx:0,vy:0,vz:0,owner:3,lastTeam:0};state.controlled=3;state.players[3].has=true}
function nearest(team,x=state.ball.x,z=state.ball.z){let best=-1,bd=1e9;state.players.forEach((p,i)=>{if(p.team!==team)return;const d=(p.x-x)**2+(p.z-z)**2;if(d<bd){bd=d;best=i}});return best}
function switchPlayer(){const n=nearest(0);if(n>=0)state.controlled=n}
function kick(kind){const p=state.players[state.controlled];if(!p||state.ball.owner!==state.controlled)return;let tx,tz;if(kind==='shot'){tx=51.5;tz=Math.max(-6.2,Math.min(6.2,p.z*.12))}else{const mates=state.players.filter(q=>q.team===0&&q!==p).sort((a,b)=>((b.x-p.x)*1.7-Math.abs(b.z-p.z))-((a.x-p.x)*1.7-Math.abs(a.z-p.z)));const target=mates[0];tx=target?target.x:Math.min(47,p.x+18);tz=target?target.z:p.z}let dx=tx-p.x,dz=tz-p.z,l=Math.hypot(dx,dz)||1;dx/=l;dz/=l;state.ball.owner=-1;p.has=false;const power=kind==='shot'?35:24;state.ball.vx=dx*power;state.ball.vz=dz*power;state.ball.vy=kind==='shot'?4.8:1.1;state.ball.lastTeam=0;p.cool=.2;if(navigator.vibrate)navigator.vibrate(kind==='shot'?18:10)}
function ai(dt){state.players.forEach((p,i)=>{p.cool=Math.max(0,p.cool-dt);if(i===state.controlled&&p.team===0)return;let tx,tz;if(state.ball.owner===i){const dir=p.team?-1:1;tx=p.x+dir*11;tz=p.z*.84;if((p.team===1&&p.x<-33)||(p.team===0&&p.x>33)){if(Math.random()<dt*.9){state.ball.owner=-1;p.has=false;let gx=p.team?-51.5:51.5,gz=(Math.random()-.5)*12,l=Math.hypot(gx-p.x,gz-p.z);state.ball.vx=(gx-p.x)/l*30;state.ball.vz=(gz-p.z)/l*30;state.ball.vy=3.8;state.ball.lastTeam=p.team}}}else{const chase=nearest(p.team)===i;if(chase){tx=state.ball.x;tz=state.ball.z}else{const base=[-39,-21,-21,-6,-6][p.i]*(p.team?-1:1),bz=[0,-18,18,-9,9][p.i];tx=base+state.ball.x*(p.i===0?.1:.34);tz=bz+state.ball.z*.2}}const dx=tx-p.x,dz=tz-p.z,l=Math.hypot(dx,dz)||1,s=p.i===0?8.4:10.5;p.vx+=(dx/l*s-p.vx)*Math.min(1,dt*4);p.vz+=(dz/l*s-p.vz)*Math.min(1,dt*4)})}
function update(dt){if(!state.running||state.paused)return;if(mode!=='training'){state.time+=dt;if(state.time>=state.duration){state.time=state.duration;finishMatch();return}}else state.time+=dt;const cp=state.players[state.controlled];let mx=state.joy.x,mz=state.joy.y,ml=Math.hypot(mx,mz);if(ml>1){mx/=ml;mz/=ml}const speed=state.sprint?14.5:10.6;cp.vx+=(mx*speed-cp.vx)*Math.min(1,dt*8);cp.vz+=(mz*speed-cp.vz)*Math.min(1,dt*8);ai(dt);state.players.forEach(p=>{p.x+=p.vx*dt;p.z+=p.vz*dt;p.x=Math.max(-48.8,Math.min(48.8,p.x));p.z=Math.max(-30.5,Math.min(30.5,p.z));p.vx*=Math.pow(.86,dt*8);p.vz*=Math.pow(.86,dt*8);if(Math.hypot(p.vx,p.vz)>.25)p.face=Math.atan2(p.vz,p.vx)});if(state.ball.owner>=0){const p=state.players[state.ball.owner],dir=p.team?-1:1;state.ball.x=p.x+dir*1.35;state.ball.z=p.z;state.ball.y=.64;state.ball.vx=p.vx;state.ball.vz=p.vz;state.ball.vy=0}else{state.ball.x+=state.ball.vx*dt;state.ball.z+=state.ball.vz*dt;state.ball.y+=state.ball.vy*dt;state.ball.vy-=15.5*dt;if(state.ball.y<.62){state.ball.y=.62;if(Math.abs(state.ball.vy)>1)state.ball.vy*=-.38;else state.ball.vy=0;state.ball.vx*=Math.pow(.985,dt*60);state.ball.vz*=Math.pow(.985,dt*60)}if(Math.abs(state.ball.z)>31.5){state.ball.z=Math.sign(state.ball.z)*31.5;state.ball.vz*=-.55}for(let i=0;i<state.players.length;i++){const p=state.players[i];if(p.cool>0||state.ball.y>1.5)continue;const d=Math.hypot(p.x-state.ball.x,p.z-state.ball.z);if(d<1.7&&Math.hypot(state.ball.vx,state.ball.vz)<25){state.ball.owner=i;p.has=true;state.ball.lastTeam=p.team;if(p.team===0)state.controlled=i;break}}}if(state.ball.owner>=0){const o=state.players[state.ball.owner];for(let i=0;i<state.players.length;i++){const p=state.players[i];if(p.team===o.team||i===state.ball.owner)continue;if(Math.hypot(p.x-o.x,p.z-o.z)<1.55&&Math.random()<dt*.75){o.has=false;p.has=true;state.ball.owner=i;state.ball.lastTeam=p.team;if(p.team===0)state.controlled=i;break}}}if(Math.abs(state.ball.x)>50.4){if(Math.abs(state.ball.z)<7.55&&state.ball.y<3.45){const scoring=state.ball.x>0?0:1;state.score[scoring]++;toast('GOAL!');resetKickoff(scoring?0:1)}else{state.ball.x=Math.sign(state.ball.x)*49.5;state.ball.vx*=-.55}}updateHud()}
function resetKickoff(teamKick){state.players.forEach(p=>p.has=false);const form=[[-39,0],[-21,-18],[-21,18],[-6,-9],[-6,9]];state.players.forEach(p=>{const [x,z]=form[p.i];p.x=p.team?-x:x;p.z=z;p.vx=p.vz=0});Object.assign(state.ball,{x:0,y:.62,z:0,vx:0,vy:0,vz:0});const idx=teamKick?8:3;state.ball.owner=idx;state.players[idx].has=true;if(!teamKick)state.controlled=idx}
function syncVisuals(dt,t){state.players.forEach((p,i)=>{const v=playerMeshes[i];if(!v)return;v.position.set(p.x,0,p.z);v.rotation.y=-p.face;const sp=Math.hypot(p.vx,p.vz),swing=Math.sin(t*.012+i)*Math.min(.75,sp*.07);v.userData.legs[0].rotation.z=swing;v.userData.legs[1].rotation.z=-swing;v.position.y=Math.abs(Math.sin(t*.012+i))*Math.min(.08,sp*.008)});if(ballMesh){ballMesh.position.set(state.ball.x,state.ball.y,state.ball.z);const hs=Math.hypot(state.ball.vx,state.ball.vz);ballMesh.rotation.z+=hs*dt*.85;ballMesh.rotation.x+=state.ball.vz*dt*.25}if(indicator){const p=state.players[state.controlled];indicator.position.set(p.x,.08,p.z);indicator.material.opacity=.72+.25*Math.sin(t*.008)}const p=state.players[state.controlled],speed=Math.hypot(p.vx,p.vz),zoom=state.sprint?1.7:0;const desired=new THREE.Vector3(p.x-14-zoom,12.2+zoom*.35,p.z+17.2);const look=new THREE.Vector3(p.x+8+speed*.16,1.15,p.z+state.joy.y*3.6);camera.position.lerp(desired,1-Math.pow(.002,dt));const currentTarget=camera.userData.target||look.clone();currentTarget.lerp(look,1-Math.pow(.003,dt));camera.userData.target=currentTarget;camera.lookAt(currentTarget)}
function updateHud(){$('#homeName').textContent=teams[state.homeTeam].short;$('#awayName').textContent=teams[state.awayTeam].short;$('#score').textContent=`${state.score[0]} — ${state.score[1]}`;const sec=mode==='training'?Math.floor(state.time):Math.max(0,Math.floor(state.duration-state.time));$('#time').textContent=mode==='training'?'FREE':`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function finishMatch(){state.running=false;cancelAnimationFrame(raf);const[a,b]=state.score,won=a>b;let text=`${teams[state.homeTeam].name} ${a}–${b} ${teams[state.awayTeam].name}`;$('#resultTitle').textContent=a===b?'Draw':won?'Victory':'Defeat';$('#resultText').textContent=text;$('#nextCup').style.display='none';if(mode==='tournament'&&won){cupStage++;localStorage.pitch27CupStage=cupStage;if(cupStage<3){$('#resultTitle').textContent='Cup win';$('#resultText').textContent=text+` • Round ${cupStage+1} awaits.`;$('#nextCup').style.display='block'}else{$('#resultTitle').textContent='Champions!';$('#resultText').textContent=text+' • You won the PITCH Cup.';cupStage=0;localStorage.pitch27CupStage=0}}if(mode==='tournament'&&!won){cupStage=0;localStorage.pitch27CupStage=0}$('#resultOverlay').classList.add('show')}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);syncVisuals(dt,t);renderer.render(scene,camera);if(state.running&&!state.paused)raf=requestAnimationFrame(loop);else if(state.paused)renderer.render(scene,camera)}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1200)}
const joy=$('#joy'),knob=joy.querySelector('.joy-knob');let joyId=null;function joyMove(e){const r=joy.getBoundingClientRect(),x=e.clientX-(r.left+r.width/2),y=e.clientY-(r.top+r.height/2),m=Math.min(r.width*.34,Math.hypot(x,y)),a=Math.atan2(y,x),nx=Math.cos(a)*m,ny=Math.sin(a)*m;knob.style.transform=`translate(${nx}px,${ny}px)`;state.joy.x=nx/(r.width*.34);state.joy.y=ny/(r.height*.34)}joy.onpointerdown=e=>{joyId=e.pointerId;joy.setPointerCapture(e.pointerId);joyMove(e)};joy.onpointermove=e=>{if(e.pointerId===joyId)joyMove(e)};joy.onpointerup=joy.onpointercancel=e=>{if(e.pointerId===joyId){joyId=null;state.joy.x=state.joy.y=0;knob.style.transform=''}};function bindHold(id,setter){const el=$(id);el.onpointerdown=e=>{el.setPointerCapture(e.pointerId);el.classList.add('down');setter(true)};el.onpointerup=el.onpointercancel=()=>{el.classList.remove('down');setter(false)}}bindHold('#sprint',v=>state.sprint=v);$('#shoot').onpointerdown=e=>{e.preventDefault();kick('shot')};$('#pass').onpointerdown=e=>{e.preventDefault();kick('pass')};$('#switch').onpointerdown=e=>{e.preventDefault();switchPlayer()};
const keys={};addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=1;if(e.key===' ')kick('shot');if(e.key.toLowerCase()==='x')kick('pass');if(e.key.toLowerCase()==='q')switchPlayer()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=0);setInterval(()=>{if(!state.running)return;state.joy.x=(keys.d?1:0)-(keys.a?1:0);state.joy.y=(keys.s?1:0)-(keys.w?1:0);state.sprint=!!keys.shift},16);
$('#pause').onclick=()=>{if(!state.running)return;state.paused=true;cancelAnimationFrame(raf);$('#pauseOverlay').classList.add('show')};$('#resume').onclick=()=>{state.paused=false;$('#pauseOverlay').classList.remove('show');last=performance.now();raf=requestAnimationFrame(loop)};$('#restart').onclick=()=>startMatch();$('#quit').onclick=()=>{state.running=false;cancelAnimationFrame(raf);show('menu')};$('#again').onclick=()=>startMatch();$('#nextCup').onclick=()=>startMatch();$('#resultMenu').onclick=()=>{state.running=false;show('menu')};
try{init3D();console.info('PITCH27_3D_READY',THREE.REVISION,quality)}catch(err){console.error(err);alert('3D engine could not start: '+String(err?.message||err))}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});