(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let state={blob:null,url:null,blueprint:null,renderInfo:null,bpmTouched:false};
const metrics={'1.0':[84,76,74,70,78],'1.5':[91,92,88,86,88],'1.5+':[97,97,97,96,97]};
function activeModel(){return $('.model.active')?.dataset.model||'1.0'}
function status(text,kind=''){const e=$('#status');if(e){e.textContent=text;e.className='inlineStatus'+(kind?' '+kind:'')}}
function setProgress(v){const e=$('#renderProgress');if(e)e.style.width=Math.max(0,Math.min(100,v))+'%'}
function setMetrics(m){const a=metrics[m]||metrics['1.0'];['m1','m2','m3','m4','m5'].forEach((id,i)=>{const e=$('#'+id);if(e)e.textContent=a[i]+'%'})}
function updateModelBadge(){const m=activeModel();const b=$('#modelBadge');if(b)b.textContent='Nova '+m;setMetrics(m)}
$$('.model').forEach(x=>x.addEventListener('click',()=>setTimeout(updateModelBadge,0)));updateModelBadge();
$('#bpm')?.addEventListener('input',()=>{state.bpmTouched=true},{capture:true});
$('#style')?.addEventListener('change',()=>{if(state.bpmTouched)return;const p=window.NovaCore?.parseStyle($('#style').value,$('#prompt')?.value||'');if(p?.bpm){$('#bpm').value=Math.round(p.bpm);$('#bpmV').textContent=Math.round(p.bpm)}});
async function generate(){const style=$('#style')?.value.trim()||'',prompt=$('#prompt')?.value.trim()||'';if(!style&&!prompt){status('Add a Style or song idea first.','bad');return}const btn=$('#generate');btn.disabled=true;$('#render')?.classList.add('show');setProgress(3);status('Nova Core is reading your Style…');try{const model=activeModel(),explicitBpm=/\b\d{2,3}\s*bpm\b/i.test(style),manualBpm=state.bpmTouched||explicitBpm?Number($('#bpm')?.value||118):undefined,blueprint=window.NovaCore.plan({style,prompt,model,duration:Number($('#length')?.value||20),bpm:manualBpm,energy:Number($('#energy')?.value||76)});state.blueprint=blueprint;if(!state.bpmTouched){$('#bpm').value=Math.round(blueprint.tempo);$('#bpmV').textContent=Math.round(blueprint.tempo)}$('#trackTitle').textContent='Nova '+model+' · '+blueprint.style.label;$('#trackInfo').textContent=`Nova blueprint · ${blueprint.bars} bars · ${blueprint.events.melody.length} melody events · ${blueprint.events.drums.length} drum events`;setProgress(18);status('Nova composition locked. Loading external instrument timbres only…');const out=await window.NovaRenderer.render(blueprint,{onProgress:p=>{setProgress(18+p.value*.78);if(p.stage==='samples')status('Loading external instrument timbres…');else if(p.stage==='schedule')status('Playing Nova-written notes through renderer…');else if(p.stage==='render')status('Rendering Nova arrangement…')}});if(state.url)URL.revokeObjectURL(state.url);state.blob=out.blob;state.url=URL.createObjectURL(out.blob);state.renderInfo=out;$('#player').src=state.url;$('#download').disabled=false;setMetrics(model);setProgress(100);const external=out.externalInstruments>0?`${out.externalInstruments} external timbres`:'internal timbre fallback';$('#trackInfo').textContent=`${Math.round(blueprint.tempo)} BPM · ${blueprint.style.rhythm}/${blueprint.style.harmony} · ${blueprint.style.lead} lead · ${external} · composition 100% Nova`;status('Track ready · composition and arrangement by Nova','ok');window.__novaLastBlueprint=blueprint}catch(e){console.error(e);setProgress(0);status('Render failed: '+e.message,'bad');$('#trackInfo').textContent='Nova Core could not complete this render.'}finally{btn.disabled=false}}
const oldGenerate=$('#generate');if(oldGenerate){const fresh=oldGenerate.cloneNode(true);oldGenerate.replaceWith(fresh);fresh.addEventListener('click',generate)}
const oldDownload=$('#download');if(oldDownload){const fresh=oldDownload.cloneNode(true);oldDownload.replaceWith(fresh);fresh.disabled=true;fresh.addEventListener('click',()=>{if(!state.url)return;const a=document.createElement('a');a.href=state.url;a.download='nova-'+activeModel()+'-'+(state.blueprint?.style.rhythm||'track')+'.wav';a.click()})}
window.NovaHybrid={generate,getBlueprint:()=>state.blueprint,getRenderInfo:()=>state.renderInfo,getState:()=>({...state})};
})();