import {STRINGS,MISSION,SHOP,WORLD} from './data.js?v=v3-motion-home-2';
import {TimeSystem,EconomySystem,MissionSystem,TrafficSystem,WitnessSystem,PoliceSystem,SaveSystem,makeSnapshot,restoreSnapshot,uiTextForMission} from './systems.js?v=v3-motion-home-2';
import {createWorld,setDoorOpen,updatePedestrians,updateTraffic,updatePolice} from './world.js?v=v3-motion-home-2';

const B=window.BABYLON;
const $=id=>document.getElementById(id);
const touchDevice=matchMedia('(pointer:coarse)').matches||('ontouchstart' in window)||navigator.maxTouchPoints>0;
const canvas=$('game');
const engine=new B.Engine(canvas,true,{preserveDrawingBuffer:false,stencil:true,powerPreference:'high-performance'});
if(touchDevice)engine.setHardwareScalingLevel(1.55);
const scene=new B.Scene(engine);scene.gravity=new B.Vector3(0,-.35,0);scene.skipPointerMovePicking=true;
const hemi=new B.HemisphericLight('hemi',new B.Vector3(0,1,0),scene);hemi.intensity=.9;
const sun=new B.DirectionalLight('sun',new B.Vector3(-.5,-1,.35),scene);sun.position=new B.Vector3(30,45,-25);sun.intensity=1.08;
const shadow=new B.ShadowGenerator(touchDevice?512:1024,sun);shadow.useBlurExponentialShadowMap=true;shadow.blurKernel=touchDevice?12:24;
const world=createWorld(scene);[world.player,...world.pedestrians,...world.traffic,world.driveCar].forEach(m=>shadow.addShadowCaster(m,true));world.ground.receiveShadows=true;
const camera=new B.FollowCamera('camera',new B.Vector3(0,4,-7),scene);camera.radius=4.1;camera.heightOffset=2.05;camera.rotationOffset=180;camera.cameraAcceleration=.08;camera.maxCameraSpeed=11;camera.fov=.9;camera.checkCollisions=true;camera.collisionRadius=new B.Vector3(.3,.3,.3);camera.lockedTarget=world.player;scene.activeCamera=camera;

const timeSystem=new TimeSystem(WORLD.startTime),economy=new EconomySystem(),mission=new MissionSystem(),trafficSystem=new TrafficSystem(),witnessSystem=new WitnessSystem(),policeSystem=new PoliceSystem(),saveSystem=new SaveSystem();
const keys=new Set();
const touch={x:0,z:0,run:false,pointer:null};
const playerMotion={vx:0,vz:0,yaw:world.player.rotation.y||0};
let started=false,inVehicle=false,lastInteraction=0,lastNpcIncident=0,dialogTimer=0,toastTimer=0,breakfastBought=false,stamina=100,health=100;

const damp=(from,to,speed,dt)=>B.Scalar.Lerp(from,to,1-Math.exp(-speed*dt));
function wrapAngle(a){while(a>Math.PI)a-=Math.PI*2;while(a<-Math.PI)a+=Math.PI*2;return a;}
function dampAngle(from,to,speed,dt){return from+wrapAngle(to-from)*(1-Math.exp(-speed*dt));}

window.addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='KeyE'&&started)interact();if(e.code==='KeyR'&&started)resetMission();if(e.code==='F5'&&started){e.preventDefault();saveGame();}});
window.addEventListener('keyup',e=>keys.delete(e.code));
window.addEventListener('resize',()=>engine.resize());
document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();touch.x=0;touch.z=0;touch.run=false;resetKnob();}});
canvas.addEventListener('contextmenu',e=>e.preventDefault());

const dist2D=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
const arabicDigits=v=>String(v).replace(/\d/g,d=>'٠١٢٣٤٥٦٧٨٩'[d]);
const mobilePrompt=text=>touchDevice?String(text).replaceAll('اضغط E','اضغط تفاعل'):text;
function showToast(text,secs=2.4){$('toast').textContent=text;$('toast').classList.add('show');toastTimer=secs;}
function showDialogue(speaker,text,secs=3.2){$('speaker').textContent=speaker;$('dialogueText').textContent=text;$('dialogue').hidden=false;dialogTimer=secs;}
const showNpcLine=(name,text)=>showDialogue(name,text,2.2);
function hidePrompt(){$('prompt').classList.remove('show');$('prompt').textContent='';}
function showPrompt(text){$('prompt').textContent=mobilePrompt(text);$('prompt').classList.add('show');}

function resetKnob(){const knob=$('knob');if(knob)knob.style.transform='translate3d(0,0,0)';}
function bindMobileControls(){
  const joy=$('joy'),knob=$('knob'),act=$('act'),run=$('run');if(!joy||!knob||!act||!run)return;
  const updateJoy=e=>{const r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,max=r.width*.34;let dx=e.clientX-cx,dy=e.clientY-cy;const mag=Math.hypot(dx,dy)||1;if(mag>max){dx=dx/mag*max;dy=dy/mag*max;}touch.x=Math.max(-1,Math.min(1,dx/max));touch.z=Math.max(-1,Math.min(1,-dy/max));knob.style.transform=`translate3d(${dx}px,${dy}px,0)`;};
  const endJoy=e=>{if(touch.pointer!==null&&e.pointerId!==touch.pointer)return;touch.pointer=null;touch.x=0;touch.z=0;resetKnob();};
  joy.addEventListener('pointerdown',e=>{e.preventDefault();touch.pointer=e.pointerId;try{joy.setPointerCapture(e.pointerId);}catch{}updateJoy(e);});joy.addEventListener('pointermove',e=>{if(touch.pointer===e.pointerId){e.preventDefault();updateJoy(e);}});joy.addEventListener('pointerup',endJoy);joy.addEventListener('pointercancel',endJoy);joy.addEventListener('lostpointercapture',endJoy);
  const runOn=e=>{e.preventDefault();touch.run=true;run.classList.add('pressed');try{run.setPointerCapture(e.pointerId);}catch{}};const runOff=e=>{e.preventDefault();touch.run=false;run.classList.remove('pressed');};run.addEventListener('pointerdown',runOn);run.addEventListener('pointerup',runOff);run.addEventListener('pointercancel',runOff);run.addEventListener('lostpointercapture',runOff);
  act.addEventListener('pointerdown',e=>{e.preventDefault();act.classList.add('pressed');if(started)interact();try{act.setPointerCapture(e.pointerId);}catch{}});const actOff=e=>{e.preventDefault();act.classList.remove('pressed');};act.addEventListener('pointerup',actOff);act.addEventListener('pointercancel',actOff);act.addEventListener('lostpointercapture',actOff);
}
bindMobileControls();

function updateHud(){$('money').textContent=`${arabicDigits(economy.cash)} ج`;$('health').textContent=`${arabicDigits(Math.round(health))}٪`;$('stamina').textContent=`${arabicDigits(Math.round(stamina))}٪`;$('heat').textContent=policeSystem.label();const [h,m]=timeSystem.label.split(':');$('time').textContent=`${arabicDigits(h)}:${arabicDigits(m)}`;$('day').textContent=`اليوم ${arabicDigits(timeSystem.day)}`;$('missionTitle').textContent=mission.completed?STRINGS.complete:MISSION.title;$('objective').textContent=uiTextForMission(mission);$('objectiveProgress').style.setProperty('--p',`${mission.progress()}%`);}
function applyDayNight(){const h=timeSystem.hour,daylight=Math.max(.12,Math.sin(((h-6)/12)*Math.PI));sun.intensity=.25+daylight*.93;hemi.intensity=.31+daylight*.6;scene.clearColor=new B.Color4(.09+.47*daylight,.13+.57*daylight,.19+.63*daylight,1);const night=h>=18.5||h<6;for(const lamp of world.lightPoles){if(lamp.material)lamp.material.emissiveColor=night?new B.Color3(1,.72,.35):new B.Color3(0,0,0);}}

function inputAxes(){const kx=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0);const kz=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0);let x=Math.max(-1,Math.min(1,kx+touch.x)),z=Math.max(-1,Math.min(1,kz+touch.z));const len=Math.hypot(x,z);if(len>1){x/=len;z/=len;}return{x,z};}
function updateCamera(dt){const p=inVehicle?world.driveCar.position:world.player.position;const nearApartment=!inVehicle&&p.x>-29.5&&p.x<-14.5&&p.z>-20.2&&p.z<-8.6;const targetRadius=inVehicle?6.4:(nearApartment?3.25:4.7),targetHeight=inVehicle?2.6:(nearApartment?1.95:2.2);camera.radius=damp(camera.radius,targetRadius,4.8,dt);camera.heightOffset=damp(camera.heightOffset,targetHeight,4.8,dt);}
function playerMove(dt){
  const p=world.player,{x,z}=inputAxes(),running=(keys.has('ShiftLeft')||keys.has('ShiftRight')||touch.run);
  if(inVehicle){const car=world.driveCar,keyboardSteer=(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)-(keys.has('KeyD')||keys.has('ArrowRight')?1:0),steer=Math.max(-1,Math.min(1,keyboardSteer-touch.x));const desiredSpeed=z>=0?z*8.2:z*3.2;car.metadata.speed=damp(car.metadata.speed||0,desiredSpeed,z===0?3.4:2.35,dt);car.metadata.steer=damp(car.metadata.steer||0,steer,5.5,dt);const grip=Math.min(1,Math.abs(car.metadata.speed)/3.6);if(Math.abs(car.metadata.speed)>.12)car.metadata.heading+=car.metadata.steer*grip*1.18*dt*Math.sign(car.metadata.speed);const dir=new B.Vector3(Math.sin(car.metadata.heading),0,Math.cos(car.metadata.heading));car.moveWithCollisions(dir.scale(car.metadata.speed*dt));car.rotation.y=car.metadata.heading;p.position.copyFrom(car.position);camera.lockedTarget=car;updateCamera(dt);return;}
  const movingInput=Math.hypot(x,z)>.04,targetSpeed=movingInput?(running&&stamina>1?5.0:3.5):0;playerMotion.vx=damp(playerMotion.vx,x*targetSpeed,movingInput?10:14,dt);playerMotion.vz=damp(playerMotion.vz,z*targetSpeed,movingInput?10:14,dt);const actualSpeed=Math.hypot(playerMotion.vx,playerMotion.vz);if(actualSpeed>.05){p.moveWithCollisions(new B.Vector3(playerMotion.vx*dt,0,playerMotion.vz*dt));const targetYaw=Math.atan2(playerMotion.vx,playerMotion.vz);playerMotion.yaw=dampAngle(playerMotion.yaw,targetYaw,12,dt);p.rotation.y=playerMotion.yaw;}if(running&&actualSpeed>.35)stamina=Math.max(0,stamina-dt*11);else stamina=Math.min(100,stamina+dt*9);camera.lockedTarget=p;updateCamera(dt);
}

function updateMission(){const p=inVehicle?world.driveCar.position:world.player.position,step=mission.current()?.id;if(!step||mission.failed||mission.completed)return;if(step==='leave_apartment'&&p.z>-10.15){mission.advance(step);showToast('تمام. دلوقتي روح للمحل.');}else if(step==='reach_shop_side'&&dist2D(p,{x:WORLD.crossingX,z:-5})<3.4){mission.advance(step);showToast('استنى إشارة المشاة تبقى خضرا.');}else if(step==='cross_safely'&&p.z>4.2&&Math.abs(p.x-WORLD.crossingX)<5){if(trafficSystem.pedestrianGreen){mission.advance(step);showToast('عدّيت بأمان. كمل للمحل.');}else{mission.fail('عدّيت والإشارة مش سامحة');showToast('المهمة فشلت — عدّيت والإشارة مش سامحة',4);}}else if(step==='enter_shop'&&p.z>9.4&&p.z<17&&p.x>14.5&&p.x<25.5){mission.advance(step);showDialogue('عم صابر','صباح الفل يا باشا، أطلبلك إيه؟',4);showToast('اتكلم مع عم صابر');}else if(step==='return_home'&&dist2D(p,WORLD.homeReturn)<3.2){mission.advance(step);economy.earn(MISSION.reward);showToast(`المهمة خلصت — كسبت ${MISSION.reward} جنيه`,4);saveGame(false);}}
function nearestInteraction(){const p=inVehicle?world.driveCar.position:world.player.position;if(inVehicle)return {type:'car_exit'};const candidates=[{type:'apt_door',d:dist2D(p,world.aptDoor.position)},{type:'shop_door',d:dist2D(p,world.shopDoor.position)},{type:'cashier',d:dist2D(p,world.cashier.position)},{type:'car',d:dist2D(p,world.driveCar.position)}].filter(v=>v.d<2.25).sort((a,b)=>a.d-b.d);return candidates[0]||null;}
function interact(){const now=performance.now();if(now-lastInteraction<220)return;lastInteraction=now;const i=nearestInteraction();if(!i){showToast('مفيش حاجة تتفاعل معاها هنا',1.4);return;}if(i.type==='car'){inVehicle=true;world.player.setEnabled(false);world.driveCar.metadata.speed=0;world.driveCar.metadata.steer=0;showToast('ركبت العربية');}else if(i.type==='car_exit'){inVehicle=false;world.player.setEnabled(true);world.player.position.copyFrom(world.driveCar.position.add(new B.Vector3(2,0,0)));world.player.position.y=WORLD.playerStart.y;playerMotion.vx=0;playerMotion.vz=0;playerMotion.yaw=world.driveCar.metadata.heading;camera.lockedTarget=world.player;showToast('نزلت من العربية');}else if(i.type==='apt_door'){setDoorOpen(world.aptDoor,!world.aptDoor.metadata.open);showToast(world.aptDoor.metadata.open?'فتحت الباب':'قفلت الباب');}else if(i.type==='shop_door'){setDoorOpen(world.shopDoor,!world.shopDoor.metadata.open);showToast(world.shopDoor.metadata.open?'فتحت باب المحل':'قفلت باب المحل');}else if(i.type==='cashier')openShop();}
function openShop(){if(mission.current()?.id!=='buy_breakfast'&&!breakfastBought){showDialogue('عم صابر','لفّ شوية في المحل الأول وتعالى لي.',3);return;}const body=$('modalBody');body.innerHTML=`<p><strong>${SHOP.cashier}:</strong> صباح الفل يا باشا، أطلبلك إيه؟</p><p>${SHOP.items[0].name} — <strong>${SHOP.items[0].price} جنيه</strong></p><button id="buyBreakfast" class="primary">هات الفطار</button>`;$('modalTitle').textContent=SHOP.name;$('modal').hidden=false;$('buyBreakfast').onclick=()=>{if(breakfastBought){showToast('الفطار معاك خلاص');return;}if(!economy.pay(SHOP.items[0].price)){showToast('معاكش فلوس كفاية');return;}breakfastBought=true;if(mission.current()?.id==='buy_breakfast')mission.advance('buy_breakfast');$('modal').hidden=true;showDialogue('عم صابر','اتفضل يا باشا. خلي بالك من نفسك وإنت راجع.',4);showToast('خدت الفطار — ارجع ناحية البيت');};}
function updatePrompt(){const i=nearestInteraction();if(!i){hidePrompt();return;}if(i.type==='car')showPrompt(STRINGS.enterCar);else if(i.type==='car_exit')showPrompt(STRINGS.exitCar);else if(i.type==='apt_door'||i.type==='shop_door')showPrompt(i.type==='apt_door'?(world.aptDoor.metadata.open?'اضغط E تقفل باب الشقة':'اضغط E تفتح باب الشقة'):(world.shopDoor.metadata.open?'اضغط E تقفل باب المحل':'اضغط E تفتح باب المحل'));else if(i.type==='cashier')showPrompt('اضغط E واتكلم مع عم صابر');}

function detectIncidents(){if(!inVehicle)return;const now=performance.now();for(const p of world.pedestrians){if(dist2D(p.position,world.driveCar.position)<1.35&&now-lastNpcIncident>5000){lastNpcIncident=now;showNpcLine(p.metadata.name,'إيه يا عم براحة!');witnessSystem.report('reckless_driving',world.driveCar.position,1);showToast('حد بلغ عن سواقة متهورة');break;}}}
function resetMission(){mission.reset();breakfastBought=false;inVehicle=false;world.player.setEnabled(true);world.player.position.set(WORLD.playerStart.x,WORLD.playerStart.y,WORLD.playerStart.z);playerMotion.vx=0;playerMotion.vz=0;playerMotion.yaw=0;world.player.rotation.y=0;world.driveCar.position.set(-7,.5,-7);world.driveCar.metadata.speed=0;world.driveCar.metadata.steer=0;world.driveCar.metadata.heading=0;world.driveCar.rotation.y=0;policeSystem.heat=0;policeSystem.active=false;setDoorOpen(world.aptDoor,false);setDoorOpen(world.shopDoor,false);camera.lockedTarget=world.player;showToast('بدأت المهمة من الأول');}
function saveGame(notify=true){saveSystem.save(makeSnapshot({player:world.player,mission,economy,time:timeSystem,police:policeSystem,inVehicle}));if(notify)showToast(STRINGS.save);}
function loadGame(){const s=saveSystem.load();if(!s){$('bootStatus').textContent=STRINGS.noSave;return false;}restoreSnapshot(s,{player:world.player,mission,economy,time:timeSystem,police:policeSystem});breakfastBought=mission.index>=5||mission.completed;inVehicle=false;world.player.setEnabled(true);world.player.position.y=WORLD.playerStart.y;playerMotion.vx=0;playerMotion.vz=0;playerMotion.yaw=world.player.rotation.y||0;setDoorOpen(world.aptDoor,mission.index>=1);setDoorOpen(world.shopDoor,mission.index>=4||world.player.position.z>9.2);showToast(STRINGS.load);return true;}
function start(load=false){if(load&&!loadGame())return;started=true;$('boot').hidden=true;$('hud').hidden=false;canvas.focus();updateHud();}

$('newGame').onclick=()=>{resetMission();start(false);};$('continueGame').onclick=()=>start(true);$('saveBtn').onclick=()=>saveGame();
$('howTo').onclick=()=>{$('modalTitle').textContent='التحكم';$('modalBody').innerHTML=touchDevice?'<p><strong>العصاية:</strong> حركة تدريجية<br><strong>جري:</strong> اضغط واستمر<br><strong>تفاعل:</strong> افتح الأبواب واركب العربية واتكلم</p>':'<p><strong>WASD / الأسهم:</strong> حركة<br><strong>Shift:</strong> جري<br><strong>E:</strong> تفاعل أو فتح الأبواب أو ركوب/نزول العربية<br><strong>R:</strong> إعادة المهمة<br><strong>F5:</strong> حفظ سريع</p>';$('modal').hidden=false;};$('closeModal').onclick=()=>{$('modal').hidden=true;};
window.__SHWARE3_DEBUG={state:()=>({build:'v3-motion-home-2',ready:!!window.__SHWARE3_READY,started,inVehicle,touchDevice,engineSource:window.__SHWARE3_ENGINE_SOURCE,player:{x:world.player.position.x,y:world.player.position.y,z:world.player.position.z},camera:{x:camera.position.x,y:camera.position.y,z:camera.position.z,radius:camera.radius},playerSpeed:Math.hypot(playerMotion.vx,playerMotion.vz),mission:mission.current()?.id||null,meshes:scene.meshes.length,traffic:world.traffic.map(v=>({x:v.position.x,z:v.position.z,speed:v.metadata.currentSpeed}))}),interact:()=>interact()};
engine.runRenderLoop(()=>{const frameDt=Math.min(Math.max(engine.getDeltaTime()/1000,0),.2);if(started){const steps=Math.max(1,Math.min(4,Math.ceil(frameDt/.05))),dt=frameDt/steps;for(let i=0;i<steps;i++){timeSystem.update(dt);trafficSystem.update(dt);playerMove(dt);updatePedestrians(world.pedestrians,dt,world.player,showNpcLine);updateTraffic(world.traffic,dt,trafficSystem);detectIncidents();witnessSystem.update(dt,policeSystem);policeSystem.update(dt,inVehicle?world.driveCar.position:world.player.position);updatePolice(world,policeSystem,dt);updateMission();}world.trafficLight.set(trafficSystem.carGreen);updatePrompt();applyDayNight();updateHud();if(dialogTimer>0&&(dialogTimer-=frameDt)<=0)$('dialogue').hidden=true;if(toastTimer>0&&(toastTimer-=frameDt)<=0)$('toast').classList.remove('show');}scene.render();});
scene.executeWhenReady(()=>{window.__SHWARE3_READY=true;window.__SHWARE3_BOOT_FAILED=false;for(const id of ['newGame','continueGame','howTo']){const b=$(id);if(b)b.disabled=false;}$('bootStatus').textContent=touchDevice?'V3.1 جاهزة — الكاميرا محمية من الحيطان':'V3.1 جاهزة — اضغط لعبة جديدة';const fatal=$('fatalError');if(fatal)fatal.hidden=true;});
window.addEventListener('beforeunload',()=>{if(started)saveGame(false);});
