(() => {
  'use strict';

  const canvas = document.getElementById('game');
  const $ = id => document.getElementById(id);
  const ui = {
    money:$('money'), hungerTxt:$('hungerTxt'), hungerBar:$('hungerBar'), energyTxt:$('energyTxt'), energyBar:$('energyBar'), moodTxt:$('moodTxt'), moodBar:$('moodBar'),
    time:$('time'), day:$('day'), taskTitle:$('taskTitle'), taskText:$('taskText'), prompt:$('prompt'), toast:$('toast'), map:$('minimap'),
    menu:$('menu'), newGame:$('newGameBtn'), cont:$('continueBtn'), reset:$('resetBtn'), menuStatus:$('menuStatus'),
    shop:$('shop'), shopTitle:$('shopTitle'), shopDesc:$('shopDesc'), shopItems:$('shopItems'), shopClose:$('shopClose'),
    dialog:$('dialog'), dialogWho:$('dialogWho'), dialogText:$('dialogText'), dialogClose:$('dialogClose'), error:$('errorBox'),
    joy:$('joy'), knob:$('knob'), act:$('act'), run:$('run')
  };

  if (!window.BABYLON) {
    ui.error.style.display='block';
    ui.error.textContent='تعذر تحميل محرك اللعبة. تأكد من اتصال الإنترنت ثم أعد تحميل الصفحة.';
    return;
  }

  const isTouch = matchMedia('(pointer: coarse)').matches || 'ontouchstart' in window;
  const SAVE_KEY='hayat-masr-v3';
  const DEFAULT_STATE={money:300,hunger:82,energy:91,mood:74,minute:8*60+15,day:1,task:0,breakfast:false,worked:0,market:false,savedX:-6,savedZ:8};
  const shops=[
    {name:'فول وطعمية أبو علي',type:'ful',sign:'#8a3f24',desc:'فطار مصري سريع مع عيش بلدي.',items:[['ساندوتش فول',14,22,3],['ساندوتش طعمية',12,18,4],['طبق فول',25,34,4],['بطاطس',16,18,5]]},
    {name:'كشري الحبايب',type:'koshary',sign:'#b33d32',desc:'رز ومكرونة وعدس وحمص وصلصة وبصل.',items:[['كشري صغير',35,32,5],['كشري كبير',52,48,8],['رز بلبن',24,15,8]]},
    {name:'قهوة الحارة',type:'ahwa',sign:'#5b3b24',desc:'شاي وقهوة وطاولة وكراسي على الرصيف.',items:[['شاي كُشري',10,1,7],['شاي بالنعناع',13,1,9],['قهوة سادة',18,0,12],['قعدة طاولة',8,0,9]]},
    {name:'فرن العيش البلدي',type:'bakery',sign:'#8d6235',desc:'عيش سخن وفطار بسيط.',items:[['رغيف عيش بلدي',3,7,1],['فطيرة جبنة',30,24,4],['قرص سادة',14,10,2]]},
    {name:'عصير ولاد البلد',type:'juice',sign:'#2f7b54',desc:'قصب وبرتقال ومانجا ساقعين.',items:[['قصب',18,0,12],['برتقال',25,1,11],['مانجا',32,3,14]]},
    {name:'كشك عم صابر',type:'kiosk',sign:'#315b89',desc:'مياه وسناكس ومناديل وحاجات سريعة.',items:[['مياه',7,0,3],['بسكوت',10,7,2],['عصير',15,2,7],['مناديل',8,0,1]]},
    {name:'بقالة الأمانة',type:'grocery',sign:'#486d37',desc:'احتياجات البيت اليومية.',items:[['جبنة بيضا وعيش',30,22,3],['زبادي',12,9,3],['حلاوة',18,14,4],['مياه كبيرة',10,0,4]]},
    {name:'خضار وفاكهة البركة',type:'produce',sign:'#3c783d',desc:'خضار وفاكهة من قلب السوق.',items:[['موز',25,12,5],['برتقال',22,8,5],['طماطم وخيار',28,10,3]]},
    {name:'كبدة إسكندراني',type:'kebda',sign:'#9a442d',desc:'ساندوتشات كبدة سريعة.',items:[['ساندوتش كبدة',32,26,7],['بطاطس',16,18,4]]}
  ];
  const sayings=[
    ['عم سيد','صباح الفل يا ابني، الحق عربية الفول قبل الزحمة.'],
    ['أم محمود','خد بالك وإنت معدّي الشارع، الميكروباص بيظهر فجأة 😄'],
    ['الحاج رضا','الدنيا حر النهارده… قصب ساقع يعدّل المزاج.'],
    ['مينا','الماتش بالليل على القهوة، هتلاقي نص الحارة هناك.'],
    ['عم رجب','العيش لسه طالع سخن من الفرن.'],
    ['سارة','لو رايح السوق هات طماطم وخيار وإنت راجع.'],
    ['المعلم شوقي','الشغل عايز حركة يا نجم، خد طلبية ولف الحارة.'],
    ['نجلاء','بليل الشارع بيهدى شوية، بس القهوة بتفضل منورة.']
  ];
  const weekdays=['السبت','الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة'];

  let state=loadState();
  let engine,scene,camera,sun,hemi,sky;
  let current=null,modal=false,sprinting=false,toastTimer=0,lastSave=0,joyX=0,joyY=0,joyPointer=null,lookPointer=null,lastPX=0,lastPY=0;
  const world={size:228,roads:[-90,-54,-18,18,54,90],interactables:[],shops:[],people:[],vehicles:[],lights:[],home:null,job:null,market:{x:54,z:-54}};
  const mats=new Map();

  function loadState(){try{return Object.assign({},DEFAULT_STATE,JSON.parse(localStorage.getItem(SAVE_KEY)||'{}'));}catch{return {...DEFAULT_STATE};}}
  function saveState(){if(!camera)return;state.savedX=+camera.position.x.toFixed(2);state.savedZ=+camera.position.z.toFixed(2);localStorage.setItem(SAVE_KEY,JSON.stringify(state));}
  function hasSave(){return !!localStorage.getItem(SAVE_KEY);}
  function resetState(){state={...DEFAULT_STATE};if(camera){camera.position.set(DEFAULT_STATE.savedX,1.72,DEFAULT_STATE.savedZ);camera.rotation.set(0,0,0);}updateHUD();}
  function clamp(v,a=0,b=100){return Math.max(a,Math.min(b,v));}

  function mat(name,hex,emit){const key=name+hex+(emit||'');if(mats.has(key))return mats.get(key);const m=new BABYLON.StandardMaterial(key,scene);m.diffuseColor=BABYLON.Color3.FromHexString(hex);m.specularColor=new BABYLON.Color3(.04,.04,.04);if(emit)m.emissiveColor=BABYLON.Color3.FromHexString(emit);mats.set(key,m);return m;}
  function box(name,w,h,d,x,y,z,material,collision=true){const m=BABYLON.MeshBuilder.CreateBox(name,{width:w,height:h,depth:d},scene);m.position.set(x,y,z);m.material=material;m.checkCollisions=collision;return m;}
  function cyl(name,dia,h,x,y,z,material,tess=12){const m=BABYLON.MeshBuilder.CreateCylinder(name,{diameter:dia,height:h,tessellation:tess},scene);m.position.set(x,y,z);m.material=material;m.checkCollisions=true;return m;}
  function sign(text,x,y,z,width=6,height=1,bg='#4d3425',rot=Math.PI){const tex=new BABYLON.DynamicTexture('signTex'+Math.random(),{width:700,height:150},scene,false);const c=tex.getContext();c.fillStyle=bg;c.fillRect(0,0,700,150);c.fillStyle='#fff3d2';c.font='bold 64px Tahoma,Arial';c.textAlign='center';c.textBaseline='middle';c.direction='rtl';c.fillText(text,350,78);tex.update();const sm=new BABYLON.StandardMaterial('signMat'+Math.random(),scene);sm.diffuseTexture=tex;sm.emissiveColor=new BABYLON.Color3(.15,.13,.1);sm.backFaceCulling=false;const p=BABYLON.MeshBuilder.CreatePlane('sign',{width,height},scene);p.position.set(x,y,z);p.rotation.y=rot;p.material=sm;p.isPickable=false;return p;}

  function buildScene(){
    engine=new BABYLON.Engine(canvas,true,{antialias:true,adaptToDeviceRatio:true});
    scene=new BABYLON.Scene(engine);scene.collisionsEnabled=true;scene.gravity=new BABYLON.Vector3(0,-.24,0);scene.clearColor=new BABYLON.Color4(.76,.82,.87,1);scene.fogMode=BABYLON.Scene.FOGMODE_EXP2;scene.fogDensity=.0023;scene.fogColor=new BABYLON.Color3(.76,.78,.78);

    // Human-scale camera: 1.72 m eye height, collider centered below the eyes.
    camera=new BABYLON.UniversalCamera('player',new BABYLON.Vector3(state.savedX,1.72,state.savedZ),scene);
    camera.minZ=.06;camera.fov=.90;camera.speed=.28;camera.inertia=.48;camera.angularSensibility=3800;camera.applyGravity=true;camera.checkCollisions=true;
    camera.ellipsoid=new BABYLON.Vector3(.43,.85,.43);camera.ellipsoidOffset=new BABYLON.Vector3(0,-.82,0);camera.keysUp=[87];camera.keysDown=[83];camera.keysLeft=[65];camera.keysRight=[68];

    hemi=new BABYLON.HemisphericLight('ambient',new BABYLON.Vector3(0,1,0),scene);hemi.intensity=.62;hemi.groundColor=new BABYLON.Color3(.34,.28,.22);
    sun=new BABYLON.DirectionalLight('sun',new BABYLON.Vector3(-.45,-1,-.3),scene);sun.position.set(60,100,40);sun.intensity=1.25;
    const skyMat=mat('sky','#7fa7c3','#273945');skyMat.backFaceCulling=false;skyMat.disableLighting=true;sky=BABYLON.MeshBuilder.CreateSphere('sky',{diameter:650,segments:14},scene);sky.material=skyMat;sky.infiniteDistance=true;sky.isPickable=false;
    const ground=BABYLON.MeshBuilder.CreateGround('ground',{width:world.size,height:world.size},scene);ground.material=mat('ground','#b3a27d');ground.checkCollisions=true;

    buildRoads();buildBuildings();buildMarket();buildAhwa();buildLandmarks();buildStreetProps();buildVehicles();buildPeople();
    scene.onBeforeRenderObservable.add(update);
    return scene;
  }

  function buildRoads(){const asphalt=mat('asphalt','#4b4a47'),walk=mat('walk','#b9b0a2'),mark=mat('mark','#ddd7c8');for(const r of world.roads){box('rv',10,.08,world.size,r,.04,0,asphalt,false);box('sv1',2.1,.15,world.size,r-6.05,.08,0,walk,true);box('sv2',2.1,.15,world.size,r+6.05,.08,0,walk,true);box('rh',world.size,.08,10,0,.045,r,asphalt,false);box('sh1',world.size,.15,2.1,0,.08,r-6.05,walk,true);box('sh2',world.size,.15,2.1,0,.08,r+6.05,walk,true);for(let n=-105;n<=105;n+=9){box('dashv',.12,.02,3,r,.1,n,mark,false);box('dashh',3,.02,.12,n,.105,r,mark,false);}}}

  function buildBuildings(){const centers=[-72,-36,0,36,72];const colors=['#d1bd99','#c2a27d','#d0c0a8','#b99373','#c9b18e','#bda78d'];let si=0;for(const x of centers)for(const z of centers){if((x===72&&z===-36)||(x===36&&z===-72))continue;const seed=Math.abs(x*13+z*17),floors=4+(seed%3),w=21+(seed%4),d=20+((seed>>2)%4),h=floors*3.0;box('building',w,h,d,x,h/2,z,mat('bld'+seed,colors[seed%colors.length]),true);box('roof',w+.1,.45,d+.1,x,h+.23,z,mat('roof','#a89275'),false);addRoofDetails(x,z,h,w,d,seed);for(let f=1;f<floors;f++)for(let c=-1;c<=1;c++){const wx=x+c*w*.25,wy=f*3+1.32,wz=z-d/2-.07;box('window',2.05,1.25,.12,wx,wy,wz,mat('window','#34434a','#091115'),false);if((f+c+seed)%2===0)addBalcony(wx,wy,z-d/2,seed+f+c);if((f+c+seed)%4===1)addAC(wx+1.35,wy-.2,wz);}const count=3,sw=w/count;for(let s=0;s<count;s++){const sx=x-w/2+sw*(s+.5),shop=shops[(si+s)%shops.length];box('front',sw-.35,2.45,.22,sx,1.35,z-d/2-.14,mat('front'+shop.type,shop.sign),false);sign(shop.name,sx,3.05,z-d/2-.28,Math.min(sw-.25,7.2),.9,shop.sign);const hot=box('hot',sw-.45,2.6,1.2,sx,1.35,z-d/2-.85,mat('hot','#fff'),false);hot.visibility=0;const e={mesh:hot,kind:'shop',name:shop.name,data:shop,x:sx,z:z-d/2-1};world.interactables.push(e);world.shops.push(e);if(shop.type==='kiosk')decorateKiosk(sx,z-d/2-1.65);if(shop.type==='produce')decorateProduce(sx,z-d/2-1.65);if(shop.type==='bakery')decorateBread(sx,z-d/2-1.6);}si+=3;}}

  function addRoofDetails(x,z,h,w,d,seed){for(let i=0;i<2;i++){const t=cyl('tank',1.35,1.7,x-w*.22+i*3,h+1.05,z+d*.14,mat('tank','#252d31'),12);t.checkCollisions=false;}const pole=cyl('dishPole',.07,.7,x+w*.2,h+.65,z-d*.1,mat('metal','#777'),8);pole.checkCollisions=false;const dish=BABYLON.MeshBuilder.CreateDisc('dish',{radius:.62,tessellation:18},scene);dish.position.set(x+w*.2,h+1,z-d*.1);dish.rotation.x=1.05;dish.rotation.z=seed*.1;dish.material=mat('dish','#d2ccc0');dish.isPickable=false;}
  function addBalcony(x,y,front,seed){box('balcony',3.4,.14,1.05,x,y-.72,front-.56,mat('balcony','#c5b39b'),false);box('rail',3,.06,.06,x,y-.13,front-1.05,mat('rail','#45413d'),false);for(const r of [-1,0,1])box('rp',.06,.62,.06,x+r*1.35,y-.43,front-1.05,mat('rail','#45413d'),false);if(seed%3===0)for(let i=-2;i<=2;i++)box('cloth',.48,.62,.025,x+i*.54,y-.05-(i%2)*.05,front-1.09,mat('cloth'+i,['#eee4d4','#5f7798','#aa5a50','#d8c250','#66805b'][i+2]),false);}
  function addAC(x,y,z){box('ac',.92,.55,.34,x,y,z,mat('ac','#ddd9cf'),false);for(let i=-2;i<=2;i++)box('vent',.65,.02,.02,x,y+i*.065,z-.18,mat('dark','#555'),false);}
  function decorateKiosk(x,z){for(let i=-2;i<=2;i++)box('pack',.38,.42,.3,x+i*.42,.24,z,mat('pack'+i,['#bd4d3e','#d2b342','#4b82a4','#7c9c55','#b96b3e'][i+2]),false);}
  function decorateProduce(x,z){for(let i=-2;i<=2;i++){box('crate',.85,.45,.62,x+i*.9,.25,z,mat('crate','#87613d'),false);const f=BABYLON.MeshBuilder.CreateSphere('fruit',{diameter:.26,segments:6},scene);f.position.set(x+i*.9,.58,z);f.material=mat('fruit'+i,i%2?'#d05b38':'#7d9d42');f.isPickable=false;}}
  function decorateBread(x,z){for(let i=-1;i<=1;i++){box('tray',1,.06,.5,x+i*1.05,.42,z,mat('tray','#777'),false);for(let j=-1;j<=1;j++){const b=BABYLON.MeshBuilder.CreateSphere('bread',{diameter:.36,segments:8},scene);b.scaling.y=.35;b.position.set(x+i*1.05+j*.28,.54,z);b.material=mat('bread','#c99250');b.isPickable=false;}}}

  function buildMarket(){const x=54,z=-54;sign('سوق الحارة',x,4.2,z+15,7,1,'#8a4d2d',0);for(let i=0;i<4;i++){const sx=x-13.5+i*9;box('stall',6.5,.7,3.5,sx,.38,z+3,mat('stall','#795337'),true);box('shade',6.5,.1,4,sx,2.7,z+3,mat('shade'+i,i%2?'#c79b3e':'#b94b3b'),false);decorateProduce(sx,z+.8);}const hot=box('marketHot',31,2.4,24,x,1.2,z,mat('hot','#fff'),false);hot.visibility=0;world.interactables.push({mesh:hot,kind:'market',name:'سوق الحارة',x,z});}
  function buildAhwa(){const x=-54,z=54;sign('قهوة المعلم فتحي',x,3.5,z-13,7,.9,'#5d3923',0);for(let r=0;r<2;r++)for(let c=0;c<4;c++){const px=x-6.5+c*4.3,pz=z-7+r*4;const t=cyl('table',1.05,.72,px,.36,pz,mat('table','#725033'),10);t.checkCollisions=false;for(const ox of [-.9,.9])box('chair',.52,.72,.52,px+ox,.36,pz,mat('chair','#68472f'),false);}}
  function buildLandmarks(){const h=box('home',2.1,2.8,.25,-72,1.4,-82.1,mat('door','#5a3924'),false);sign('بيت العيلة',-72,3.35,-82.25,3.2,.72,'#5a3924');world.home={mesh:h,kind:'home',name:'بيت العيلة',x:-72,z:-82};world.interactables.push(world.home);const j=box('job',3.5,2.2,1.8,-18,1.1,54,mat('job','#25616a'),true);sign('طلبات الحارة',-18,2.75,53.05,4,.8,'#25616a');world.job={mesh:j,kind:'job',name:'شغل التوصيل',x:-18,z:54};world.interactables.push(world.job);buildFulCart(-8,-8);const mosque=box('mosque',13,6,11,90,3,90,mat('mosque','#d8cdb3'),true);mosque.isPickable=false;const dome=BABYLON.MeshBuilder.CreateSphere('dome',{diameter:5.5,segments:16,slice:.55},scene);dome.position.set(90,7.15,90);dome.material=mat('dome','#829a83');cyl('minaret',1.6,13,96,6.5,91,mat('minaret','#d7c7a6'),12);}
  function buildFulCart(x,z){box('cart',2.6,.8,1.4,x,.55,z,mat('cart','#477658'),true);const p=cyl('pot',.9,.65,x,.84,z,mat('pot','#8a8982'),14);p.checkCollisions=false;sign('فول وطعمية',x,1.7,z-.78,2.7,.55,'#477658');const hot=box('fulhot',2.8,2,2,x,1,z,mat('hot','#fff'),false);hot.visibility=0;world.interactables.push({mesh:hot,kind:'shop',name:'عربية فول وطعمية',x,z,data:shops[0]});}
  function buildStreetProps(){for(const x of world.roads)for(const z of world.roads){const px=x+7.5,pz=z+7.5;const pole=cyl('lamp',.12,5,px,2.5,pz,mat('lamp','#494744'),8);pole.checkCollisions=false;const b=BABYLON.MeshBuilder.CreateSphere('bulb',{diameter:.42,segments:7},scene);b.position.set(px,5.1,pz);b.material=mat('bulb','#fff0bd','#6d5728');world.lights.push(b);}for(let i=0;i<14;i++){const x=-102+(i*31)%204,z=-102+(i*47)%204;box('crate',.9,.55,.7,x,.29,z,mat('crate','#8a633f'),true);}}

  function makeVehicle(type,i){const vertical=i%2===0,lane=world.roads[i%world.roads.length]+(i%3===0?2.2:-2.2),along=-108+(i*29)%216,root=new BABYLON.TransformNode(type+'Root',scene);root.position=vertical?new BABYLON.Vector3(lane,.58,along):new BABYLON.Vector3(along,.58,lane);root.rotation.y=vertical?0:Math.PI/2;let w=1.78,h=1.15,d=3.9,col='#e9e8e3',speed=.11;if(type==='micro'){w=2.05;h=1.65;d=5;speed=.09;}if(type==='tuktuk'){w=1.3;h=1.5;d=2.2;col=['#28688a','#a64039','#4d7043'][i%3];speed=.075;}if(type==='taxi'){col='#f0efea';speed=.1;}const body=box(type,w,h,d,0,.12,0,mat(type+col,col),false);body.parent=root;const wind=box('wind',w*.84,.5,.06,0,.42,-d/2-.01,mat('glass','#24323a','#081115'),false);wind.parent=root;if(type==='taxi'){const stripe=box('stripe',w+.02,.16,d*.72,0,.08,0,mat('stripe','#222'),false);stripe.parent=root;}for(const sx of [-1,1])for(const sz of [-1,1]){const wh=BABYLON.MeshBuilder.CreateCylinder('wheel',{diameter:.52,height:.2,tessellation:10},scene);wh.parent=root;wh.position.set(sx*w*.47,-.34,sz*d*.3);wh.rotation.z=Math.PI/2;wh.material=mat('wheel','#171717');}return{root,vertical,dir:i%3===0?-1:1,speed};}
  function buildVehicles(){const types=['micro','taxi','car','tuktuk','car','micro'];for(let i=0;i<18;i++)world.vehicles.push(makeVehicle(types[i%types.length],i));}
  function makePerson(x,z,i){const root=new BABYLON.TransformNode('personRoot',scene);root.position.set(x,0,z);const cols=['#455f77','#744e40','#45684a','#6b4b71','#817047','#4b4b4b'];const body=BABYLON.MeshBuilder.CreateCapsule('person',{radius:.3,height:1.55,tessellation:8},scene);body.parent=root;body.position.y=.92;body.material=mat('shirt'+i,cols[i%cols.length]);const head=BABYLON.MeshBuilder.CreateSphere('head',{diameter:.46,segments:8},scene);head.parent=root;head.position.y=1.78;head.material=mat('skin','#b98563');const data={root,axis:i%2,dir:i%3===0?-1:1,speed:.018+(i%4)*.004,phase:i*.7,name:sayings[i%sayings.length][0],line:sayings[i%sayings.length][1]};world.interactables.push({kind:'person',name:data.name,data,root});return data;}
  function buildPeople(){for(let i=0;i<24;i++)world.people.push(makePerson(-100+(i*23)%200,-100+(i*37)%200,i));}

  function update(){const dt=Math.min(engine.getDeltaTime(),50)/16.6667;if(!modal&&ui.menu.style.display==='none'){updateNeeds(dt);updateVehicles(dt);updatePeople(dt);updateInteraction();updateTouchMovement(dt);}updateDayNight();updateHUD();drawMap();const now=performance.now();if(now-lastSave>12000&&ui.menu.style.display==='none'){saveState();lastSave=now;}}
  function updateNeeds(dt){const moving=camera.cameraDirection.lengthSquared()>.0003;state.hunger=clamp(state.hunger-.0024*dt);state.energy=clamp(state.energy-(moving?(sprinting?.0045:.0018):-.0006)*dt);if(state.hunger<25)state.mood=clamp(state.mood-.0012*dt);state.minute+=.012*dt;if(state.minute>=1440){state.minute-=1440;state.day++;}}
  function updateVehicles(dt){for(const v of world.vehicles){if(v.vertical){v.root.position.z+=v.speed*v.dir*dt;if(v.root.position.z>116)v.root.position.z=-116;if(v.root.position.z<-116)v.root.position.z=116;}else{v.root.position.x+=v.speed*v.dir*dt;if(v.root.position.x>116)v.root.position.x=-116;if(v.root.position.x<-116)v.root.position.x=116;}}}
  function nearestRoad(v){return world.roads.reduce((a,b)=>Math.abs(b-v)<Math.abs(a-v)?b:a,world.roads[0]);}
  function updatePeople(dt){for(const p of world.people){if(p.axis===0){p.root.position.x+=p.speed*p.dir*dt;p.root.position.z=nearestRoad(p.root.position.z)+(p.phase%2?7:-7);if(p.root.position.x>108)p.root.position.x=-108;if(p.root.position.x<-108)p.root.position.x=108;p.root.rotation.y=p.dir>0?Math.PI/2:-Math.PI/2;}else{p.root.position.z+=p.speed*p.dir*dt;p.root.position.x=nearestRoad(p.root.position.x)+(p.phase%2?7:-7);if(p.root.position.z>108)p.root.position.z=-108;if(p.root.position.z<-108)p.root.position.z=108;p.root.rotation.y=p.dir>0?0:Math.PI;}}}
  function updateTouchMovement(dt){if(!isTouch||modal)return;const f=camera.getDirection(BABYLON.Axis.Z);f.y=0;f.normalize();const r=camera.getDirection(BABYLON.Axis.X);r.y=0;r.normalize();let v=f.scale(joyY).add(r.scale(joyX));if(v.lengthSquared()>.001){v.normalize();camera.cameraDirection.addInPlace(v.scale((sprinting?.32:.20)*dt));}}

  function itemPos(i){if(i.root)return i.root.position;if(i.mesh)return i.mesh.position;return new BABYLON.Vector3(i.x||0,0,i.z||0);}
  function updateInteraction(){let best=null,bestD=2.9;for(const i of world.interactables){const p=itemPos(i),d=Math.hypot(p.x-camera.position.x,p.z-camera.position.z);if(d<bestD){bestD=d;best=i;}}current=best;ui.prompt.classList.toggle('show',!!best);if(best)ui.prompt.textContent=`${isTouch?'تفاعل':'E'} — ${best.name}`;}
  function interact(){if(modal){closeModals();return;}if(!current)return;if(current.kind==='shop')openShop(current.data);else if(current.kind==='person')openDialog(current.data.name,current.data.line);else if(current.kind==='market'){state.market=true;showToast('لفّيت في سوق الحارة 👌');advanceTask('market');}else if(current.kind==='job')startJob();else if(current.kind==='home'){state.energy=100;state.hunger=Math.max(state.hunger,62);state.minute+=60;showToast('رجعت بيت العيلة وارتحت');advanceTask('home');saveState();}}
  function openShop(data){modal=true;ui.shopTitle.textContent=data.name;ui.shopDesc.textContent=data.desc;ui.shopItems.innerHTML='';for(const [name,price,hunger,mood] of data.items){const row=document.createElement('div');row.className='item';row.innerHTML=`<div><b>${name}</b><div style="font-size:11px;opacity:.66">${price} جنيه</div></div>`;const b=document.createElement('button');b.textContent='اشتري';b.onclick=()=>{if(state.money<price){showToast('الفلوس مش مكفية');return;}state.money-=price;state.hunger=clamp(state.hunger+hunger);state.mood=clamp(state.mood+mood);state.minute+=7;if(['ful','bakery','koshary'].includes(data.type)){state.breakfast=true;advanceTask('breakfast');}showToast(`اشتريت ${name}`);saveState();};row.appendChild(b);ui.shopItems.appendChild(row);}ui.shop.style.display='flex';}
  function openDialog(who,text){modal=true;ui.dialogWho.textContent=who;ui.dialogText.textContent=text;ui.dialog.style.display='flex';state.mood=clamp(state.mood+1);}
  function closeModals(){modal=false;ui.shop.style.display='none';ui.dialog.style.display='none';}
  function startJob(){if(state.energy<18){showToast('طاقتك قليلة، كل أو ارجع البيت الأول');return;}const pay=45+Math.floor(Math.random()*31);state.energy=clamp(state.energy-10);state.money+=pay;state.worked++;state.minute+=35;showToast(`خلصت طلبية وكسبت ${pay} جنيه`);advanceTask('job');saveState();}
  function advanceTask(action){if(state.task===0&&action==='breakfast'){state.task=1;showToast('فطار تمام 👌 روح السوق');}else if(state.task===1&&action==='market'){state.task=2;showToast('عرفت السوق — جرّب شغل التوصيل');}else if(state.task===2&&action==='job'){state.task=3;showToast('خلصت الشغل — ارجع بيت العيلة');}else if(state.task===3&&action==='home'){state.task=4;showToast('خلصت أول يوم في الحارة 🇪🇬');}}
  function taskCopy(){switch(state.task){case 0:return['أول يوم في الحارة','اتمشّى وافطر فول وطعمية أو عيش بلدي أو كشري.'];case 1:return['لفة السوق','روح سوق الحارة ناحية الشرق واتفرج على الباعة.'];case 2:return['رزق اليوم','روح «طلبات الحارة» وخد شغلانة توصيل.'];case 3:return['ارجع للعيلة','بعد الشغل ارجع بيت العيلة وارتاح.'];default:return['عيش يومك','لف الحارة، كل، اشتغل واتكلم مع الناس.'];}}

  function updateDayNight(){const t=state.minute/1440,a=t*Math.PI*2-Math.PI/2,light=clamp(Math.sin(a)*.78+.45,.08,1);sun.direction.set(Math.cos(a)*-.55,-Math.max(.12,Math.sin(a)),Math.sin(a)*-.35);sun.intensity=.18+light*1.2;hemi.intensity=.22+light*.47;scene.fogColor=new BABYLON.Color3(.18+.58*light,.2+.59*light,.24+.55*light);if(sky&&sky.material)sky.material.emissiveColor=new BABYLON.Color3(.08+.45*light,.1+.54*light,.15+.58*light);const night=light<.35;for(const b of world.lights)b.material.emissiveColor=night?new BABYLON.Color3(.9,.65,.22):new BABYLON.Color3(.12,.1,.05);}
  function updateHUD(){ui.money.textContent=`${Math.round(state.money)} ج`;ui.hungerTxt.textContent=`${Math.round(state.hunger)}%`;ui.energyTxt.textContent=`${Math.round(state.energy)}%`;ui.moodTxt.textContent=`${Math.round(state.mood)}%`;ui.hungerBar.style.width=state.hunger+'%';ui.energyBar.style.width=state.energy+'%';ui.moodBar.style.width=state.mood+'%';const h=Math.floor(state.minute/60)%24,m=Math.floor(state.minute%60);ui.time.textContent=`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`;ui.day.textContent=`اليوم ${state.day} — ${weekdays[(state.day-1)%7]}`;const [a,b]=taskCopy();ui.taskTitle.textContent=a;ui.taskText.textContent=b;}
  function showToast(text){ui.toast.textContent=text;ui.toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>ui.toast.classList.remove('show'),2300);}
  function drawMap(){const c=ui.map,ctx=c.getContext('2d'),s=c.width,scale=s/world.size;ctx.clearRect(0,0,s,s);ctx.fillStyle='#6f6853';ctx.fillRect(0,0,s,s);ctx.fillStyle='#3f4240';for(const r of world.roads){ctx.fillRect((r+world.size/2-5)*scale,0,10*scale,s);ctx.fillRect(0,(r+world.size/2-5)*scale,s,10*scale);}ctx.fillStyle='#d3b85e';ctx.fillRect((world.market.x+world.size/2-15)*scale,(world.market.z+world.size/2-12)*scale,30*scale,24*scale);if(world.home){ctx.fillStyle='#f0d16d';ctx.fillRect((world.home.x+world.size/2)*scale-3,(world.home.z+world.size/2)*scale-3,6,6);}ctx.save();ctx.translate((camera.position.x+world.size/2)*scale,(camera.position.z+world.size/2)*scale);ctx.rotate(-camera.rotation.y);ctx.fillStyle='#fff';ctx.beginPath();ctx.moveTo(0,-6);ctx.lineTo(4,5);ctx.lineTo(-4,5);ctx.closePath();ctx.fill();ctx.restore();}

  function enterGame(newGame){if(newGame){localStorage.removeItem(SAVE_KEY);resetState();}else{state=loadState();camera.position.set(state.savedX,1.72,state.savedZ);updateHUD();}ui.menu.style.display='none';ui.menuStatus.textContent='';if(!isTouch){camera.attachControl(canvas,true);canvas.focus();canvas.requestPointerLock?.();}showToast(newGame?'بدأت يوم جديد في الحارة 🇪🇬':'رجعت لآخر مكان محفوظ');}
  function setupMenu(){ui.cont.disabled=!hasSave();ui.cont.style.opacity=hasSave()?'1':'.45';ui.cont.onclick=()=>{if(hasSave())enterGame(false);};ui.newGame.onclick=()=>enterGame(true);ui.reset.onclick=()=>{localStorage.removeItem(SAVE_KEY);ui.cont.disabled=true;ui.cont.style.opacity='.45';ui.menuStatus.textContent='تم مسح الحفظ. تقدر تبدأ يوم جديد.';resetState();};if(!hasSave())ui.menuStatus.textContent='مفيش حفظ قديم لسه — ابدأ يوم جديد.';}
  function setupInput(){addEventListener('keydown',e=>{if(e.code==='KeyE')interact();if(e.code==='ShiftLeft'||e.code==='ShiftRight'){sprinting=true;camera.speed=.46;}if(e.code==='Escape')closeModals();});addEventListener('keyup',e=>{if(e.code==='ShiftLeft'||e.code==='ShiftRight'){sprinting=false;camera.speed=.28;}});ui.shopClose.onclick=closeModals;ui.dialogClose.onclick=closeModals;ui.act.onclick=interact;ui.run.onpointerdown=()=>sprinting=true;ui.run.onpointerup=()=>sprinting=false;ui.run.onpointercancel=()=>sprinting=false;if(isTouch){ui.joy.addEventListener('pointerdown',e=>{joyPointer=e.pointerId;ui.joy.setPointerCapture(e.pointerId);setJoy(e);});ui.joy.addEventListener('pointermove',e=>{if(e.pointerId===joyPointer)setJoy(e);});const end=e=>{if(e.pointerId===joyPointer){joyPointer=null;joyX=joyY=0;ui.knob.style.transform='translate(0,0)';}};ui.joy.addEventListener('pointerup',end);ui.joy.addEventListener('pointercancel',end);canvas.addEventListener('pointerdown',e=>{lookPointer=e.pointerId;lastPX=e.clientX;lastPY=e.clientY;});canvas.addEventListener('pointermove',e=>{if(e.pointerId!==lookPointer||modal)return;const dx=e.clientX-lastPX,dy=e.clientY-lastPY;lastPX=e.clientX;lastPY=e.clientY;camera.rotation.y+=dx*.004;camera.rotation.x=clamp(camera.rotation.x+dy*.003,-1.2,1.2);});canvas.addEventListener('pointerup',e=>{if(e.pointerId===lookPointer)lookPointer=null;});}addEventListener('beforeunload',saveState);addEventListener('resize',()=>engine.resize());}
  function setJoy(e){const r=ui.joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,max=40,len=Math.hypot(dx,dy)||1,k=Math.min(1,max/len),nx=dx*k,ny=dy*k;joyX=nx/max;joyY=-ny/max;ui.knob.style.transform=`translate(${nx}px,${ny}px)`;}

  window.addEventListener('error',e=>{ui.error.style.display='block';ui.error.textContent='حصل خطأ أثناء تشغيل اللعبة: '+(e.message||'خطأ غير معروف');});
  try{buildScene();setupMenu();setupInput();updateHUD();engine.runRenderLoop(()=>scene.render());}catch(err){console.error(err);ui.error.style.display='block';ui.error.textContent='اللعبة وقفت أثناء التحميل: '+err.message;}
})();